// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Marek Cingel
// Generated by test-query-adversarial --export; source text deliberately omitted.
// clang-format off
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[3]; char source[1]; uint8_t payload[2]; } native_0 = {
{1364351282u,7u,3u,2u,0u,400u,0u,403u,0u,2u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,0u,2u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,2u,4u,0u,0u,0u,0u,1u,4294967295u,0u,9u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{9u,0u,1u,0u,2u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
}, {0}, {1,255}};
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[5]; char source[1]; uint8_t payload[4]; } native_1 = {
{1364351282u,7u,5u,4u,0u,632u,1u,637u,0u,4u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,0u,1u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,1u,3u,0u,0u,0u,0u,1u,4294967295u,0u,8u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{0u,4294967295u,4294967295u,11u,13u,0u,0u,1u,0u,2u,1u,4294967295u,0u,0u,0u,0u,2u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,3u},
{10u,1u,2u,3u,4u,0u,0u,0u,0u,1u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{8u,0u,3u,0u,1u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
}, {0}, {112,255,1,255}};
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[5]; char source[1]; uint8_t payload[2]; } native_2 = {
{1364351282u,7u,5u,4u,0u,632u,2u,635u,0u,2u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,1u,3u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,3u,5u,0u,0u,0u,0u,1u,4294967295u,0u,9u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{9u,0u,1u,1u,3u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,1u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{22u,4294967295u,4294967295u,7u,11u,0u,0u,0u,2u,3u,2u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,13u,0u,0u,0u,0u,0u},
{10u,2u,3u,6u,7u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
}, {0}, {1,255}};
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[5]; char source[1]; uint8_t payload[2]; } native_3 = {
{1364351282u,7u,5u,4u,0u,632u,3u,635u,0u,2u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,0u,2u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,2u,4u,0u,0u,0u,0u,1u,4294967295u,0u,9u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{9u,0u,1u,0u,2u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,16u,17u,10u,0u,0u,0u,3u,4294967295u,2u,8u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{8u,2u,3u,4u,5u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
}, {0}, {1,255}};
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[4]; char source[1]; uint8_t payload[2]; } native_4 = {
{1364351282u,7u,4u,3u,0u,516u,2u,519u,0u,2u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,6u,8u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,8u,10u,0u,0u,0u,0u,1u,4294967295u,0u,9u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{9u,0u,1u,6u,8u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{22u,2u,4294967295u,0u,5u,0u,1u,0u,2u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,9u,0u,0u,0u,0u,0u},
}, {0}, {1,255}};
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[4]; char source[1]; uint8_t payload[2]; } native_5 = {
{1364351282u,7u,4u,3u,0u,516u,2u,519u,0u,2u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,7u,9u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,9u,11u,0u,0u,0u,0u,1u,4294967295u,0u,9u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{9u,0u,1u,7u,9u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{22u,2u,4294967295u,0u,6u,0u,1u,0u,1u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,10u,0u,0u,0u,0u,0u},
}, {0}, {1,255}};
static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[6]; char source[1]; uint8_t payload[2]; } native_6 = {
{1364351282u,7u,6u,5u,0u,748u,2u,751u,0u,2u,0u,0u,0u}, {
{1u,4294967295u,4294967295u,6u,8u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{0u,4294967295u,4294967295u,8u,10u,0u,0u,0u,0u,1u,4294967295u,0u,9u,0u,0u,0u,0u,1u,2u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,1u},
{4u,4294967295u,4294967295u,11u,12u,0u,2u,1u,2u,2u,1u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,1u,0u,0u,0u,0u},
{10u,1u,2u,10u,11u,0u,0u,0u,0u,1u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{9u,0u,3u,6u,8u,0u,0u,0u,0u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
{22u,4u,4294967295u,0u,5u,0u,1u,0u,3u,0u,4294967295u,4294967295u,0u,0u,0u,0u,0u,0u,0u,0u,0u,4294967295u,0u,0u,0u,0u,0u,0u,0u},
}, {0}, {1,255}};
static const tlv_query_program_t* const native_plans[] = {&native_0.header, &native_1.header, &native_2.header, &native_3.header,&native_4.header, &native_5.header, &native_6.header};
// clang-format on
