// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Marek Cingel
/* Included by the C-only adversarial driver; intentionally shares CHECK/arena. */
#if OPENTLV_QUERY_FRONTEND
#include "tlv/defaults.h"
#include "tlv/format.h"
#include "tlv/formats/fixed.h"
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
#include "tlv/document/document.h"
#include "tlv/writer/tree.h"
#endif
typedef struct callback_state {
    tlv_query_exec_t* exec;
    size_t            workspace_bytes;
    unsigned          calls, errors;
    int               fail, mutation;
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
    tlv_document_t* document;
    tlv_node_t*     node;
#endif
} callback_state;
static int compile_plan(const char* source, const tlv_query_environment_t* environment,
                        arena* image, const tlv_query_program_t** p) {
    arena                       scratch;
    tlv_query_compile_options_t options;
    tlv_query_compile_options_init(&options);
    options.environment = environment;
    tlv_query_program_info_t info = {0};
    info.struct_size = sizeof info;
    CHECK(tlv_query_compile(source, strlen(source), &options, aligned(&scratch),
                            sizeof scratch.bytes - 16, aligned(image), sizeof image->bytes - 16,
                            &info, NULL) == TLV_OK);
    *p = aligned(image);
    return 0;
}
static int export_plans(void) {
    const char* sources[] = {"//01",        "/70[child::01]", "(//01)[last()]", "//01/preceding::*",
                             "count(//01)", "exists(//01)",   "value(//01[1])"};
    puts("// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Marek Cingel\n"
         "// Generated by test-query-adversarial --export; source text deliberately omitted.\n"
         "// clang-format off");
    for (size_t i = 0; i < sizeof sources / sizeof *sources; ++i) {
        arena                      image;
        const tlv_query_program_t* p;
        CHECK(compile_plan(sources[i], NULL, &image, &p) == 0);
        tlv_query_plan_t header = *p;
        header.text_size = 0;
        header.reserved = header.text_offset + 1 + header.payload_size;
        printf("static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[%u]; "
               "char source[1]; uint8_t payload[%u]; } native_%zu = {\n{",
               header.count, header.payload_size ? header.payload_size : 1, i);
        uint32_t fields[sizeof header / sizeof(uint32_t)];
        memcpy(fields, &header, sizeof header);
        for (size_t j = 0; j < sizeof fields / sizeof *fields; ++j)
            printf("%s%uu", j ? "," : "", fields[j]);
        puts("}, {");
        for (size_t n = 0; n < header.count; ++n) {
            uint32_t instruction[sizeof(tlv_query_instruction_t) / sizeof(uint32_t)];
            memcpy(instruction, (const uint8_t*)(p + 1) + n * sizeof instruction,
                   sizeof instruction);
            putchar('{');
            for (size_t j = 0; j < sizeof instruction / sizeof *instruction; ++j)
                printf("%s%uu", j ? "," : "", instruction[j]);
            puts("},");
        }
        printf("}, {0}, {");
        const uint8_t* payload = (const uint8_t*)p + p->text_offset + p->text_size + 1;
        for (size_t j = 0; j < header.payload_size; ++j) printf("%s%u", j ? "," : "", payload[j]);
        if (!header.payload_size) putchar('0');
        puts("}};");
    }
    puts("static const tlv_query_program_t* const native_plans[] = {"
         "&native_0.header, &native_1.header, &native_2.header, &native_3.header,"
         "&native_4.header, &native_5.header, &native_6.header};\n// clang-format on");
    return 0;
}
static int loader_aliases(void) {
    arena                      image, memory, before;
    const tlv_query_program_t* p;
    CHECK(compile_plan("//01", NULL, &image, &p) == 0);
    size_t bytes, alignment;
    CHECK(tlv_query_program_load_scratch(p, p->reserved, NULL, &bytes, &alignment, NULL) == TLV_OK);
    CHECK(bytes < 32768);
    const ptrdiff_t offsets[] = {0,
                                 1,
                                 -1,
                                 16,
                                 -16,
                                 (ptrdiff_t)p->reserved - 1,
                                 (ptrdiff_t)p->reserved,
                                 -(ptrdiff_t)bytes + 1,
                                 -(ptrdiff_t)bytes};
    for (size_t i = 0; i < sizeof offsets / sizeof *offsets; ++i) {
        memset(&memory, 0xa5, sizeof memory);
        uint8_t* copy = (uint8_t*)aligned(&memory) + 32768;
        memcpy(copy, p, p->reserved);
        uint8_t* scratch = copy + offsets[i];
        memcpy(&before, &memory, sizeof memory);
        const tlv_query_program_t* result = NULL;
        int                        overlap =
            offsets[i] >= 0 ? (size_t)offsets[i] < p->reserved : (size_t)-offsets[i] < bytes;
        int          invalid = overlap || (uintptr_t)scratch % alignment;
        tlv_result_t rc =
            tlv_query_program_load(copy, p->reserved, NULL, scratch, bytes, &result, NULL, NULL);
        CHECK(rc == (invalid ? TLV_ERR_INVALID_ARG : TLV_OK));
        if (invalid)
            CHECK(!result && !memcmp(&before, &memory, sizeof memory));
        else
            CHECK(result == (const tlv_query_program_t*)copy);
    }
    memset(&memory, 0xa5, sizeof memory);
    memcpy(&before, &memory, sizeof memory);
    tlv_query_program_info_t info = {0};
    info.struct_size = sizeof info;
    CHECK(tlv_query_compile("//01", 4, NULL, aligned(&memory), sizeof memory.bytes - 16,
                            aligned(&memory), 1024, &info, NULL) == TLV_ERR_INVALID_ARG);
    CHECK(!memcmp(&before, &memory, sizeof memory));
    size_t needed = 77;
    CHECK(tlv_query_compile_scratch("//01", 4, NULL, &needed, &needed, NULL) ==
          TLV_ERR_INVALID_ARG);
    CHECK(needed == 77);
    uint8_t immutable[2048];
    CHECK(p->reserved <= sizeof immutable);
    memcpy(immutable, p, p->reserved);
    CHECK(tlv_query_program_format(p, (char*)p, p->reserved, &needed) == TLV_ERR_INVALID_ARG);
    CHECK(!memcmp(immutable, p, p->reserved));
    memcpy(aligned(&memory), p, p->reserved);
    ((tlv_query_plan_t*)aligned(&memory))->version = TLV_QUERY_PLAN_VERSION - 1;
    const tlv_query_program_t* loaded = NULL;
    tlv_query_diagnostic_t     diagnostic;
    CHECK(tlv_query_program_load(aligned(&memory), p->reserved, NULL, aligned(&before), bytes,
                                 &loaded, NULL, &diagnostic) == TLV_ERR_UNSUPPORTED_TYPE);
    CHECK(!loaded && diagnostic.kind == TLV_QUERY_ERROR_IMAGE_VERSION);
    return 0;
}
static void reenter(callback_state* s) {
    tlv_tree_event_t       input = event(), out;
    tlv_query_result_t     result;
    tlv_query_diagnostic_t diagnostic;
    unsigned char          original[sizeof diagnostic];
    memset(&diagnostic, 0xa5, sizeof diagnostic);
    memcpy(original, &diagnostic, sizeof diagnostic);
    int matched = 123;
    ++s->calls;
    if (tlv_query_exec_feed(s->exec, &input, &matched, &diagnostic) != TLV_ERR_INVALID_STATE ||
        matched != 123)
        ++s->errors;
    if (memcmp(original, &diagnostic, sizeof diagnostic)) ++s->errors;
    if (tlv_query_exec_finish(s->exec, &diagnostic) != TLV_ERR_INVALID_STATE) ++s->errors;
    if (memcmp(original, &diagnostic, sizeof diagnostic)) ++s->errors;
    if (tlv_query_exec_reset(s->exec) != TLV_ERR_INVALID_STATE) ++s->errors;
    if (tlv_query_exec_bind(s->exec, "n", TLV_QUERY_RESULT_INTEGER, 1, NULL, 0, &diagnostic) !=
        TLV_ERR_INVALID_STATE)
        ++s->errors;
    if (memcmp(original, &diagnostic, sizeof diagnostic)) ++s->errors;
    if (tlv_query_exec_context(s->exec, 0) != TLV_ERR_INVALID_STATE) ++s->errors;
    if (tlv_query_exec_pruning(s->exec, 1) != TLV_ERR_INVALID_STATE) ++s->errors;
    if (tlv_query_exec_result(s->exec, &result) != TLV_ERR_INVALID_STATE) ++s->errors;
    if (tlv_query_exec_selected(s->exec, &out) != TLV_ERR_INVALID_STATE) ++s->errors;
    if (tlv_query_result_next(s->exec, &out) != TLV_ERR_INVALID_STATE) ++s->errors;
}
static tlv_result_t resolve(const void* context, const char* ns, size_t ns_size, const char* name,
                            size_t size, tlv_tag_t* tag) {
    callback_state*      s = (callback_state*)context;
    static const uint8_t byte = 1;
    (void)ns;
    (void)ns_size;
    (void)name;
    (void)size;
    reenter(s);
    if (s->fail) return TLV_ERR_INVALID_TAG;
    *tag = tlv_tag(&byte, 1);
    return TLV_OK;
}
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
static tlv_visit_result_t document_visitor(tlv_node_t*, void*);
static void               mutate(callback_state* s) {
    if (!s->document) return;
    tlv_node_t*   node = s->node;
    tlv_node_t*   parent = tlv_node_parent(node);
    const uint8_t tag = 1, value = 8;
    uint64_t      identity = tlv_node_identity(node);
    switch (s->mutation) {
        case 1: tlv_node_erase(node); break;
        case 2: tlv_node_erase(parent ? parent : node); break;
        case 3:
        case 4:
            if (tlv_node_set_value(s->mutation == 4 && parent ? parent : node, &value, 1) !=
                TLV_ERR_INVALID_STATE)
                ++s->errors;
            break;
        case 5:
        case 6:
            if (tlv_document_insert(s->document, parent,
                                    s->mutation == 5 ? node : tlv_node_next(node), tlv_tag(&tag, 1),
                                    &value, 1, NULL) != TLV_ERR_INVALID_STATE)
                ++s->errors;
            break;
        case 7:
            if (tlv_document_query_program_visit(s->exec, document_visitor, s) !=
                TLV_ERR_INVALID_STATE)
                ++s->errors;
            break;
        case 8: tlv_document_free(s->document); break;
        case 9:
            tlv_node_erase(node);
            tlv_node_erase(parent ? parent : node);
            break;
    }
    /* Erase/free are deferred: borrowed node/tag/value survive this callback. */
    if (tlv_node_identity(node) != identity || tlv_node_tag(node).size != 1) ++s->errors;
}
static tlv_visit_result_t document_visitor(tlv_node_t* node, void* context) {
    callback_state* s = context;
    s->node = node;
    reenter(s);
    mutate(s);
    return TLV_VISIT_STOP;
}
#else
static void mutate(callback_state* s) {
    (void)s;
}
#endif
static tlv_codec_result_t decode(const void* context, const tlv_tree_event_t* input,
                                 const uint8_t* data, size_t size, void* scratch, size_t capacity,
                                 tlv_query_result_t* out) {
    callback_state* s = (callback_state*)context;
    (void)input;
    (void)data;
    (void)size;
    (void)scratch;
    (void)capacity;
    reenter(s);
    mutate(s);
    /* Resolver runs at compile time. Nested independent compilation is supported,
     * but operations on the surrounding active execution still must be rejected. */
    arena                       image, workspace;
    tlv_query_environment_t     environment = {0};
    tlv_query_compile_options_t options;
    tlv_query_compile_options_init(&options);
    options.environment = &environment;
    options.resolve = resolve;
    options.resolve_context = s;
    tlv_query_program_info_t info = {0};
    info.struct_size = sizeof info;
    tlv_result_t rc =
        tlv_query_compile("//named", 7, &options, aligned(&workspace), sizeof workspace.bytes - 16,
                          aligned(&image), sizeof image.bytes - 16, &info, NULL);
    if ((s->fail && rc == TLV_OK) || (!s->fail && rc != TLV_OK)) ++s->errors;
    out->kind = TLV_QUERY_RESULT_INTEGER;
    out->integer = 1;
    return s->fail ? TLV_CODEC_ERR_INVALID_VALUE : TLV_CODEC_OK;
}
static tlv_result_t tag_number(const void* context, const tlv_tag_t* tag, int64_t* out) {
    callback_state* s = (callback_state*)context;
    reenter(s);
    mutate(s);
    *out = tag->data[0];
    return s->fail ? TLV_ERR_INVALID_TAG : TLV_OK;
}
#if OPENTLV_READER
static int constructed(const void* context, const tlv_tag_t* tag) {
    (void)context;
    return tag->size == 1 && tag->data[0] == 0x70;
}
static int same_range(const tlv_range_t* a, const tlv_range_t* b) {
    return a->offset == b->offset && a->size == b->size && a->present == b->present;
}
static int same_element(const tlv_element_t* a, const tlv_element_t* b) {
    return a->tag.data == b->tag.data && a->tag.size == b->tag.size &&
           a->value.data == b->value.data && a->value.size == b->value.size;
}
static int same_event(const tlv_tree_event_t* a, const tlv_tree_event_t* b) {
    const tlv_source_t* x = &a->source;
    const tlv_source_t* y = &b->source;
    /* Structure padding is not initialized by every Format and is not semantic. */
    return a->kind == b->kind && same_element(&a->element, &b->element) && x->data == y->data &&
           x->size == y->size && same_range(&x->header, &y->header) &&
           same_range(&x->tag, &y->tag) && same_range(&x->length, &y->length) &&
           same_range(&x->value, &y->value) && same_range(&x->trailer, &y->trailer) &&
           same_element(&x->element, &y->element) && x->format == y->format &&
           x->tag_binding == y->tag_binding && a->depth == b->depth && a->offset == b->offset &&
           a->skipped == b->skipped;
}
static tlv_visit_result_t event_visitor(const tlv_tree_event_t* input, void* context) {
    callback_state*  s = context;
    tlv_tree_event_t saved = *input;
    if ((uintptr_t)input >= (uintptr_t)s->exec &&
        (uintptr_t)input - (uintptr_t)s->exec < s->workspace_bytes)
        ++s->errors;
    reenter(s);
    if (!same_event(input, &saved)) ++s->errors;
    return TLV_VISIT_CONTINUE;
}
#endif
#if OPENTLV_READER
static tlv_visit_result_t stop_visitor(const tlv_tree_event_t* input, void* context) {
    (void)input;
    (void)context;
    return TLV_VISIT_STOP;
}
/* Query outputs may not alias Reader input, frames or Format; reject before writes. */
static int reader_aliases(void) {
    arena                      image, memory, shared, before;
    const tlv_query_program_t* p;
    CHECK(compile_plan("//01", NULL, &image, &p) == 0);
    size_t bytes, alignment;
    CHECK(tlv_query_exec_size(p, 2, &bytes, &alignment) == TLV_OK);
    memset(&shared, 0, sizeof shared);
    uint8_t*           wire = aligned(&shared);
    tlv_tree_frame_t*  frames = (tlv_tree_frame_t*)(wire + 1024);
    tlv_format_t*      format = (tlv_format_t*)(wire + 4096);
    tlv_fixed_format_t config = {
        {0}, {0, TLV_BYTE_ORDER_UNKNOWN}, TLV_ELEMENT_ORDER_TLV, TLV_LENGTH_SCOPE_VALUE};
    const uint8_t encoded[] = {0x70, 3, 1, 1, 9, 1, 1, 8};
    config.identifier.size = config.length.size = 1;
    config.length.byte_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    CHECK(tlv_fixed_format_init(format, &config) == TLV_OK);
    format->is_constructed = constructed;
    memcpy(wire, encoded, sizeof encoded);
    for (unsigned output = 0; output < 6; ++output) {
        tlv_query_exec_t* e;
        CHECK(tlv_query_exec_init(p, aligned(&memory), bytes, 2, 4, 100000, &e) == TLV_OK);
        tlv_tree_reader_t reader;
        memset(&reader, 0, sizeof reader);
        CHECK(tlv_tree_reader_init(&reader, wire, sizeof encoded, format, frames, 4, 3, 4) ==
              TLV_OK);
        int found = 77;
        /* Early return stops inside the constructed root with its frame active. */
        CHECK(tlv_query_program_exists(&reader, e, 1, &found, NULL) == TLV_OK && found == 1);
        CHECK(reader.depth == 1);
        found = 77;
        unsigned char saved_reader[sizeof reader];
        memcpy(saved_reader, &reader, sizeof reader);
        memcpy(&before, &shared, sizeof shared);
        int*                    target = &found;
        tlv_query_diagnostic_t* d = NULL;
        switch (output) {
            case 0: target = (int*)(void*)wire; break;
            case 1: target = (int*)(void*)frames; break;
            case 2: target = (int*)(void*)format; break;
            case 3: d = (tlv_query_diagnostic_t*)(void*)wire; break;
            case 4: d = (tlv_query_diagnostic_t*)(void*)frames; break;
            case 5: d = (tlv_query_diagnostic_t*)(void*)format; break;
        }
        CHECK(tlv_query_program_exists(&reader, e, 0, target, d) == TLV_ERR_INVALID_ARG);
        if (d)
            CHECK(tlv_query_program_visit(&reader, e, stop_visitor, NULL, d) ==
                  TLV_ERR_INVALID_ARG);
        CHECK(found == 77 && !memcmp(&before, &shared, sizeof shared));
        CHECK(!memcmp(saved_reader, &reader, sizeof reader));
        /* The rejected calls left the active nested cursor resumable. */
        tlv_query_diagnostic_t diagnostic;
        CHECK(tlv_query_program_exists(&reader, e, 0, &found, &diagnostic) == TLV_OK);
        CHECK(found == 1 && diagnostic.kind == TLV_QUERY_ERROR_NONE);
    }
    return 0;
}
#endif
static int callbacks(void) {
    tlv_fixed_format_t config = {
        {0}, {0, TLV_BYTE_ORDER_UNKNOWN}, TLV_ELEMENT_ORDER_TLV, TLV_LENGTH_SCOPE_VALUE};
    config.identifier.size = config.length.size = 1;
    config.length.byte_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &config) == TLV_OK);
    callback_state          state = {0};
    tlv_query_hook_t        hook = {73, TLV_QUERY_NUM, 0, 1, &state, decode};
    tlv_query_tag_adapter_t tags = {74, &state, tag_number, tag_number};
    tlv_query_environment_t environment = {0};
    environment.hooks = &hook;
    environment.hook_count = 1;
    environment.tags = &tags;
    arena                      image, memory;
    const tlv_query_program_t* p;
    const char*                expressions[] = {"num(//01)", "number(//01)", "class(//01)"};
    for (unsigned kind = 0; kind < 3; ++kind) {
        CHECK(compile_plan(expressions[kind], &environment, &image, &p) == 0);
        size_t bytes, alignment;
        CHECK(tlv_query_eval_size(p, 2, 3, &bytes, &alignment) == TLV_OK);
        CHECK(tlv_query_eval_init(p, &environment, aligned(&memory), bytes, 2, 3, 100000,
                                  &state.exec) == TLV_OK);
        for (int failed = 1; failed >= 0; --failed) {
            state.fail = failed;
            state.calls = state.errors = 0;
            CHECK(tlv_query_exec_reset(state.exec) == TLV_OK);
            tlv_tree_event_t input = event();
            int              matched;
            CHECK(tlv_query_exec_feed(state.exec, &input, &matched, NULL) == TLV_OK);
            tlv_result_t rc = tlv_query_exec_finish(state.exec, NULL);
            CHECK(failed ? rc != TLV_OK : rc == TLV_OK);
            CHECK(state.calls && !state.errors);
            tlv_query_result_t result;
            CHECK(tlv_query_exec_result(state.exec, &result) ==
                  (failed ? TLV_ERR_INVALID_STATE : TLV_OK));
            if (!failed) CHECK(result.integer == 1);
        }
    }
#if OPENTLV_READER
    format.is_constructed = constructed;
    const char* selections[] = {"//01", "/70[child::01]"};
    for (unsigned kind = 0; kind < 2; ++kind)
        for (int retained = 0; retained < 2; ++retained) {
            CHECK(compile_plan(selections[kind], NULL, &image, &p) == 0);
            size_t bytes, alignment;
            CHECK((retained ? tlv_query_eval_size(p, 2, 4, &bytes, &alignment)
                            : tlv_query_exec_size(p, 2, &bytes, &alignment)) == TLV_OK);
            CHECK((retained ? tlv_query_eval_init(p, NULL, aligned(&memory), bytes, 2, 4, 100000,
                                                  &state.exec)
                            : tlv_query_exec_init(p, aligned(&memory), bytes, 2, 4, 100000,
                                                  &state.exec)) == TLV_OK);
            state.workspace_bytes = bytes;
            const uint8_t     wire[] = {0x70, 2, 1, 0, 0x70, 2, 1, 0};
            tlv_tree_reader_t reader;
            tlv_tree_frame_t  frames[4];
            CHECK(tlv_tree_reader_init(&reader, wire, sizeof wire, &format, frames, 4, 3, 4) ==
                  TLV_OK);
            state.calls = state.errors = 0;
            CHECK(tlv_query_program_visit(&reader, state.exec, event_visitor, &state, NULL) ==
                  TLV_OK);
            CHECK(state.calls == 2 && !state.errors);
        }
#endif
    return 0;
}
typedef struct raw_init_state {
    const tlv_query_program_t*     program;
    const tlv_query_environment_t* environment;
    tlv_query_exec_t*              exec;
    size_t                         bytes;
    int                            retained, calls;
    tlv_result_t                   status;
} raw_init_state;
static void raw_reinitialize(raw_init_state* s) {
    ++s->calls;
    s->status = s->retained
                    ? tlv_query_eval_init(s->program, s->environment, s->exec, s->bytes, 2, 4,
                                          100000, &s->exec)
                    : tlv_query_exec_init(s->program, s->exec, s->bytes, 2, 4, 100000, &s->exec);
}
static tlv_result_t reinitializing_tag(const void* context, const tlv_tag_t* tag, int64_t* out) {
    (void)tag;
    raw_reinitialize((raw_init_state*)context);
    *out = 1;
    return TLV_OK;
}
static int reinitializing_constructed(const void* context, const tlv_tag_t* tag) {
    (void)tag;
    raw_reinitialize((raw_init_state*)context);
    return 0;
}
static tlv_codec_result_t reinitializing_codec(const void* context, const tlv_tree_event_t* input,
                                               const uint8_t* data, size_t size, void* scratch,
                                               size_t capacity, tlv_query_result_t* out) {
    (void)input;
    (void)data;
    (void)size;
    (void)scratch;
    (void)capacity;
    raw_reinitialize((raw_init_state*)context);
    out->kind = TLV_QUERY_RESULT_INTEGER;
    out->integer = 1;
    return TLV_CODEC_OK;
}
#if OPENTLV_READER
static tlv_visit_result_t reinitializing_event(const tlv_tree_event_t* input, void* context) {
    (void)input;
    raw_reinitialize(context);
    return TLV_VISIT_STOP;
}
#endif
static int raw_reinitialization(void) {
    arena                   image, memory;
    raw_init_state          state = {0};
    tlv_query_tag_adapter_t tags = {74, &state, reinitializing_tag, reinitializing_tag};
    tlv_query_hook_t        hook = {73, TLV_QUERY_NUM, 0, 1, &state, reinitializing_codec};
    tlv_format_t            provider_format = {0};
    provider_format.context = &state;
    provider_format.is_constructed = reinitializing_constructed;
    tlv_query_environment_t environment = {0};
    environment.tags = &tags;
    environment.hooks = &hook;
    environment.hook_count = 1;
    environment.format = &provider_format;
    state.environment = &environment;
    state.retained = 1;
    size_t                alignment;
    tlv_query_exec_info_t info = {0};
    info.struct_size = sizeof info;
    const char* expressions[] = {"//01[number(.) = 1]", "//01[class(.) = 1]", "//01[num(.) = 1]",
                                 "//01[constructed(.)]"};
    for (unsigned k = 0; k < 4; ++k) {
        CHECK(compile_plan(expressions[k], &environment, &image, &state.program) == 0);
        CHECK(tlv_query_eval_size(state.program, 2, 4, &state.bytes, &alignment) == TLV_OK);
        CHECK(tlv_query_eval_init(state.program, &environment, aligned(&memory), state.bytes, 2, 4,
                                  100000, &state.exec) == TLV_OK);
        state.calls = 0;
        tlv_tree_event_t input = event();
        int              matched;
        for (unsigned i = 0; i < 3; ++i)
            CHECK(tlv_query_exec_feed(state.exec, &input, &matched, NULL) == TLV_OK);
        tlv_query_diagnostic_t diagnostic = {0};
        tlv_result_t           rc = tlv_query_exec_finish(state.exec, &diagnostic);
        CHECK(rc == TLV_ERR_INVALID_STATE);
        CHECK(test_query_diagnostic_matches(rc, &diagnostic));
        CHECK(state.calls == 1 && state.status == TLV_OK);
        CHECK(tlv_query_exec_info(state.exec, &info) == TLV_OK && info.invalid && !info.finished);
        tlv_query_result_t result;
        CHECK(tlv_query_exec_result(state.exec, &result) == TLV_ERR_INVALID_STATE);
    }
#if OPENTLV_READER
    const char*        selections[] = {"//01", "/70[child::01]"};
    tlv_fixed_format_t config = {
        {0}, {0, TLV_BYTE_ORDER_UNKNOWN}, TLV_ELEMENT_ORDER_TLV, TLV_LENGTH_SCOPE_VALUE};
    config.identifier.size = config.length.size = 1;
    config.length.byte_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &config) == TLV_OK);
    format.is_constructed = constructed;
    for (unsigned k = 0; k < 2; ++k)
        for (state.retained = 0; state.retained < 2; ++state.retained) {
            CHECK(compile_plan(selections[k], NULL, &image, &state.program) == 0);
            CHECK((state.retained
                       ? tlv_query_eval_size(state.program, 2, 4, &state.bytes, &alignment)
                       : tlv_query_exec_size(state.program, 2, &state.bytes, &alignment)) ==
                  TLV_OK);
            state.exec = aligned(&memory);
            state.environment = NULL;
            raw_reinitialize(&state);
            CHECK(state.status == TLV_OK);
            state.calls = 0;
            const uint8_t     wire[] = {0x70, 2, 1, 0, 0x70, 2, 1, 0};
            tlv_tree_reader_t reader;
            tlv_tree_frame_t  frames[4];
            CHECK(tlv_tree_reader_init(&reader, wire, sizeof wire, &format, frames, 4, 3, 4) ==
                  TLV_OK);
            tlv_query_diagnostic_t diagnostic = {0};
            tlv_result_t rc = tlv_query_program_visit(&reader, state.exec, reinitializing_event,
                                                      &state, &diagnostic);
            CHECK(rc == TLV_ERR_INVALID_STATE);
            CHECK(test_query_diagnostic_matches(rc, &diagnostic));
            CHECK(state.calls == 1 && state.status == TLV_OK);
            CHECK(tlv_query_exec_info(state.exec, &info) == TLV_OK && info.invalid &&
                  !info.finished);
        }
#endif
    return 0;
}
#if OPENTLV_READER
typedef struct resume_visitor_state {
    size_t calls;
    int    errors;
} resume_visitor_state;
static tlv_visit_result_t resume_scale_visitor(const tlv_tree_event_t* input, void* context) {
    resume_visitor_state* state = context;
    if (input->kind != TLV_TREE_ELEMENT || input->offset != state->calls * 3 ||
        input->element.tag.size != 1 || input->element.tag.data[0] != 1 ||
        input->element.value.size != 1 || input->element.value.data[0] != 7)
        ++state->errors;
    ++state->calls;
    return TLV_VISIT_STOP;
}
static int retained_resume_scale(void) {
    enum { count = 40000 };
    /* All outputs sit between the first and later immutable input windows.
     * This deterministically exercises the borrowed envelope's legal gaps. */
    struct resume_spans {
        uint8_t                first[3];
        tlv_tree_reader_t      reader;
        tlv_tree_frame_t       frames[1];
        tlv_query_diagnostic_t diagnostic;
        int                    found;
        uint8_t                later[count - 1][3];
    } spans = {0};
    spans.first[0] = spans.first[1] = 1;
    spans.first[2] = 7;
    for (size_t i = 0; i < count - 1; ++i) memcpy(spans.later[i], spans.first, sizeof spans.first);
    tlv_fixed_format_t config = {
        {0}, {0, TLV_BYTE_ORDER_UNKNOWN}, TLV_ELEMENT_ORDER_TLV, TLV_LENGTH_SCOPE_VALUE};
    config.identifier.size = config.length.size = 1;
    config.length.byte_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &config) == TLV_OK);
    arena                      image;
    const tlv_query_program_t* p;
    /* A single axis keeps finish linear, isolating continuation overhead. */
    CHECK(compile_plan("descendant::01", NULL, &image, &p) == 0);
    size_t bytes, alignment;
    CHECK(tlv_query_eval_size(p, 1, count, &bytes, &alignment) == TLV_OK);
    void* allocation = malloc(bytes + alignment);
    CHECK(allocation);
    void* memory = (void*)(((uintptr_t)allocation + alignment - 1) & ~(uintptr_t)(alignment - 1));
    for (int mode = 0; mode < 3; ++mode) {
        tlv_query_exec_t* e;
        CHECK(tlv_query_eval_init(p, NULL, memory, bytes, 1, count, SIZE_MAX, &e) == TLV_OK);
        CHECK(tlv_tree_reader_init_incremental(&spans.reader, spans.first, sizeof spans.first,
                                               &format, spans.frames, 1, 1, count) == TLV_OK);
        resume_visitor_state visitor = {0};
        spans.found = 79;
        for (size_t i = 0; i < count; ++i) {
            if (i)
                CHECK(tlv_tree_reader_set_input(&spans.reader, spans.later[i - 1], 3, 3, 0) ==
                      TLV_OK);
            CHECK((mode ? tlv_query_program_exists(&spans.reader, e, mode == 2, &spans.found,
                                                   &spans.diagnostic)
                        : tlv_query_program_visit(&spans.reader, e, resume_scale_visitor, &visitor,
                                                  &spans.diagnostic)) == TLV_NEED_MORE_DATA);
            CHECK(visitor.calls == 0 && spans.found == 79);
        }
        CHECK(tlv_tree_reader_set_input(&spans.reader, NULL, 0, 3, 1) == TLV_OK);
        if (mode) {
            CHECK(tlv_query_program_exists(&spans.reader, e, mode == 2, &spans.found,
                                           &spans.diagnostic) == TLV_OK);
            CHECK(spans.found == 1);
        } else {
            /* STOP must also resume without rescanning all finalized nodes. */
            for (size_t i = 0; i < count; ++i) {
                CHECK(tlv_query_program_visit(&spans.reader, e, resume_scale_visitor, &visitor,
                                              &spans.diagnostic) == TLV_OK);
                CHECK(visitor.calls == i + 1 && !visitor.errors);
            }
            CHECK(tlv_query_program_visit(&spans.reader, e, resume_scale_visitor, &visitor,
                                          &spans.diagnostic) == TLV_OK);
            CHECK(visitor.calls == count);
        }
        tlv_query_exec_info_t info = {0};
        info.struct_size = sizeof info;
        CHECK(tlv_query_exec_info(e, &info) == TLV_OK);
        CHECK(info.elements == count && info.finished && !info.invalid);
    }
    free(allocation);
    return 0;
}
#endif
/* Put outputs in a legal gap between two borrowed spans. The retained envelope
 * necessarily includes them, regardless of stack/heap address ordering. */
static int retained_scale(void) {
    enum { count = 40000 };
    struct separated_spans {
        uint64_t               tag;
        int                    matched;
        tlv_query_diagnostic_t diagnostic;
        tlv_query_exec_info_t  info;
        tlv_tree_event_t       selected;
        size_t                 ordinal;
        uint64_t               value[64];
    } spans = {0};
    arena                      image;
    const tlv_query_program_t* p;
    CHECK(compile_plan("descendant::01", NULL, &image, &p) == 0);
    size_t bytes, alignment;
    CHECK(tlv_query_eval_size(p, 0, count, &bytes, &alignment) == TLV_OK);
    void* allocation = malloc(bytes + alignment);
    CHECK(allocation);
    void* memory = (void*)(((uintptr_t)allocation + alignment - 1) & ~(uintptr_t)(alignment - 1));
    tlv_query_exec_t* e;
    CHECK(tlv_query_eval_init(p, NULL, memory, bytes, 0, count, SIZE_MAX, &e) == TLV_OK);
    *(uint8_t*)&spans.tag = 1;
    tlv_tree_event_t input = event();
    input.element.tag = tlv_tag((const uint8_t*)&spans.tag, 1);
    input.element.value.data = (const uint8_t*)&spans.value;
    spans.info.struct_size = sizeof spans.info;
    for (size_t i = 0; i < count; ++i) {
        CHECK(tlv_query_exec_feed(e, &input, &spans.matched, &spans.diagnostic) == TLV_OK);
        CHECK(tlv_query_exec_info(e, &spans.info) == TLV_OK && spans.info.elements == i + 1);
    }
    CHECK(tlv_query_exec_finish(e, &spans.diagnostic) == TLV_OK);
    CHECK(tlv_query_result_next(e, (tlv_tree_event_t*)(void*)spans.value) == TLV_ERR_INVALID_ARG);
    CHECK(tlv_query_result_next_ordinal(e, &spans.selected, (size_t*)(void*)spans.value) ==
          TLV_ERR_INVALID_ARG);
    CHECK(spans.value[0] == 0);
    for (size_t i = 0; i < count; ++i) {
        CHECK(tlv_query_result_next_ordinal(e, &spans.selected, &spans.ordinal) == TLV_OK);
        CHECK(spans.ordinal == i && spans.selected.element.tag.data == input.element.tag.data);
    }
    CHECK(tlv_query_result_next(e, &spans.selected) == TLV_ERR_END_OF_BUFFER);
    free(allocation);
#if OPENTLV_READER
    CHECK(retained_resume_scale() == 0);
#endif
    return 0;
}
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
typedef struct callback_format {
    tlv_fixed_format_t config;
    callback_state*    state;
} callback_format;
static int mutating_constructed(const void* context, const tlv_tag_t* tag) {
    const callback_format* format = context;
    if (format->state) {
        reenter(format->state);
        mutate(format->state);
    }
    return constructed(NULL, tag);
}
typedef struct reinitialize_state {
    tlv_query_exec_t*          exec;
    const tlv_query_program_t* program;
    tlv_document_t*            document;
    size_t                     bytes;
    int                        mutation;
    unsigned                   calls, errors;
} reinitialize_state;
static tlv_visit_result_t reinitialize_visitor(tlv_node_t* node, void* context) {
    reinitialize_state* state = context;
    ++state->calls;
    /* Deliberately violate raw-init ownership to check defensive scope cleanup. */
    if (tlv_query_eval_init(state->program, NULL, state->exec, state->bytes, 3, 8, 100000,
                            &state->exec) != TLV_OK)
        ++state->errors;
    if (state->mutation == 1) tlv_node_erase(node);
    if (state->mutation == 2) tlv_document_free(state->document);
    return TLV_VISIT_STOP;
}
static int document_reinitialization(const tlv_document_options_t* options) {
    for (int mutation = 0; mutation < 3; ++mutation) {
        const uint8_t      wire[] = {0x70, 3, 1, 1, 9};
        reinitialize_state state = {0};
        state.mutation = mutation;
        arena image, memory;
        CHECK(compile_plan("//01", NULL, &image, &state.program) == 0);
        size_t alignment;
        CHECK(tlv_query_eval_size(state.program, 3, 8, &state.bytes, &alignment) == TLV_OK);
        CHECK(tlv_query_eval_init(state.program, NULL, aligned(&memory), state.bytes, 3, 8, 100000,
                                  &state.exec) == TLV_OK);
        CHECK(tlv_document_parse(wire, sizeof wire, options, &state.document, NULL) == TLV_OK);
        CHECK(tlv_document_query_evaluate(state.document, state.exec, NULL, NULL, 0, NULL, NULL) ==
              TLV_OK);
        CHECK(tlv_document_query_program_visit(state.exec, reinitialize_visitor, &state) ==
              TLV_ERR_INVALID_STATE);
        CHECK(state.calls == 1 && !state.errors);
        tlv_query_result_t result;
        CHECK(tlv_query_exec_result(state.exec, &result) == TLV_ERR_INVALID_STATE);
        if (mutation != 2) {
            const uint8_t value = 7, tag = 1;
            tlv_node_t*   root = tlv_document_first(state.document);
            CHECK(tlv_document_insert(state.document, root, NULL, tlv_tag(&tag, 1), &value, 1,
                                      NULL) == TLV_OK);
            CHECK(tlv_document_count(state.document) == (mutation ? 2 : 3));
            tlv_document_free(state.document);
        }
    }
    return 0;
}
/* Edit target collection may not alias the applied count or the copied Value. */
static int edit_aliases(void) {
    tlv_fixed_format_t config = {
        {0}, {0, TLV_BYTE_ORDER_UNKNOWN}, TLV_ELEMENT_ORDER_TLV, TLV_LENGTH_SCOPE_VALUE};
    config.identifier.size = config.length.size = 1;
    config.length.byte_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &config) == TLV_OK);
    tlv_document_options_t options;
    CHECK(tlv_document_options_init(&options, &format) == TLV_OK);
    arena                      image, memory;
    const tlv_query_program_t* p;
    CHECK(compile_plan("//01", NULL, &image, &p) == 0);
    size_t bytes, alignment;
    CHECK(tlv_query_eval_size(p, 3, 8, &bytes, &alignment) == TLV_OK);
    for (unsigned alias = 0; alias < 3; ++alias) {
        const uint8_t     wire[] = {1, 1, 9, 1, 1, 8};
        tlv_document_t*   document;
        tlv_query_exec_t* e;
        CHECK(tlv_document_parse(wire, sizeof wire, &options, &document, NULL) == TLV_OK);
        CHECK(tlv_query_eval_init(p, NULL, aligned(&memory), bytes, 3, 8, 100000, &e) == TLV_OK);
        CHECK(tlv_document_query_evaluate(document, e, NULL, NULL, 0, NULL, NULL) == TLV_OK);
        tlv_node_t* targets[4];
        memset(targets, 0x5a, sizeof targets);
        tlv_node_t*    saved[4];
        size_t         applied = 77;
        size_t*        count = &applied;
        const uint8_t  replacement = 4;
        const uint8_t* value = &replacement;
        memcpy(saved, targets, sizeof targets);
        switch (alias) {
            case 0: count = (size_t*)(void*)&targets[1]; break;
            case 1: value = (const uint8_t*)(void*)&targets[0]; break;
            case 2: value = (const uint8_t*)(void*)&applied; break;
        }
        CHECK(tlv_document_query_edit(document, e, TLV_DOCUMENT_QUERY_REPLACE, tlv_tag(wire, 1),
                                      value, 1, targets, 4, count) == TLV_ERR_INVALID_ARG);
        CHECK(applied == 77 && !memcmp(saved, targets, sizeof targets));
        CHECK(tlv_node_value_data(tlv_document_first(document))[0] == 9);
        CHECK(tlv_document_query_edit(document, e, TLV_DOCUMENT_QUERY_REPLACE, tlv_tag(wire, 1),
                                      &replacement, 1, targets, 4, &applied) == TLV_OK);
        CHECK(applied == 2 && tlv_node_value_data(tlv_document_first(document))[0] == 4);
        tlv_document_free(document);
    }
    return 0;
}
static int documents(void) {
    const char* expressions[] = {
        "//01",         "/70[child::01]",  "(//01)[last()]", "//01 | //01/following::*",
        "num(//01[1])", "number(//01[1])", "class(//01[1])", "constructed(//01[1])"};
    callback_format callback = {0};
    callback.config.identifier.size = callback.config.length.size = 1;
    callback.config.length.byte_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &callback.config) == TLV_OK);
    format.is_constructed = mutating_constructed;
    tlv_document_options_t options;
    CHECK(tlv_document_options_init(&options, &format) == TLV_OK);
    options.retain_source_locations = 1;
    CHECK(document_reinitialization(&options) == 0);
    CHECK(edit_aliases() == 0);
    for (unsigned kind = 0; kind < sizeof expressions / sizeof *expressions; ++kind)
        for (int mutation = 0; mutation <= 9; ++mutation) {
            const uint8_t  wire[] = {0x70, 3, 1, 1, 9};
            callback_state state = {0};
            state.mutation = mutation;
            callback.state = NULL;
            CHECK(tlv_document_parse(wire, sizeof wire, &options, &state.document, NULL) == TLV_OK);
            state.node = tlv_node_first_child(tlv_document_first(state.document));
            if (kind == 7) callback.state = &state;
            tlv_query_hook_t        hook = {73, TLV_QUERY_NUM, 0, 1, &state, decode};
            tlv_query_tag_adapter_t tags = {74, &state, tag_number, tag_number};
            tlv_query_environment_t environment = {0};
            environment.format = &format;
            environment.hooks = &hook;
            environment.hook_count = 1;
            environment.tags = &tags;
            arena                      image, memory;
            const tlv_query_program_t* p;
            CHECK(compile_plan(expressions[kind], &environment, &image, &p) == 0);
            size_t bytes, alignment;
            CHECK(tlv_query_eval_size(p, 3, 8, &bytes, &alignment) == TLV_OK);
            CHECK(tlv_query_eval_init(p, &environment, aligned(&memory), bytes, 3, 8, 100000,
                                      &state.exec) == TLV_OK);
            uint8_t                     values[64], scratch[64];
            tlv_tree_writer_frame_t     frames[8];
            tlv_tree_writer_workspace_t staging = {0};
            staging.data = values;
            staging.data_capacity = sizeof values;
            staging.scratch = scratch;
            staging.scratch_capacity = sizeof scratch;
            staging.frames = frames;
            staging.frame_capacity = 8;
            tlv_result_t rc = tlv_document_query_evaluate(state.document, state.exec, NULL, values,
                                                          sizeof values, &staging, NULL);
            if (kind < 4) {
                CHECK(rc == TLV_OK);
                rc = tlv_document_query_program_visit(state.exec, document_visitor, &state);
            }
            int invalid = mutation == 1 || mutation == 2 || mutation == 8 || mutation == 9;
            CHECK(rc == (invalid ? TLV_ERR_INVALID_STATE : TLV_OK));
            CHECK(state.calls && !state.errors);
            if (invalid) {
                tlv_query_result_t output;
                tlv_node_t*        node = NULL;
                CHECK(tlv_query_exec_result(state.exec, &output) == TLV_ERR_INVALID_STATE);
                CHECK(tlv_document_query_next(state.exec, &node) == TLV_ERR_INVALID_STATE);
            }
            CHECK(tlv_query_exec_reset(state.exec) == TLV_OK);
            if (mutation != 8) tlv_document_free(state.document);
        }
    return 0;
}
#endif
#endif
