// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Marek Cingel
/* Included by the C-only adversarial driver; intentionally shares CHECK/arena. */
#if OPENTLV_QUERY_FRONTEND
#include "tlv/defaults.h"
#include "tlv/format.h"
#include "tlv/formats/fixed.h"
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
#include "tlv/document/document.h"
#include "tlv/writer/tree.h"
#endif
typedef struct callback_state {
    tlv_query_exec_t* exec;
    unsigned          calls, errors;
    int               fail, mutation;
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
    tlv_document_t* document;
    tlv_node_t*     node;
#endif
} callback_state;
static int compile_plan(const char* source, const tlv_query_environment_t* environment,
                        arena* image, const tlv_query_program_t** p) {
    arena                       scratch;
    tlv_query_compile_options_t options;
    tlv_query_compile_options_init(&options);
    options.environment = environment;
    tlv_query_program_info_t info = {0};
    info.struct_size = sizeof info;
    CHECK(tlv_query_compile(source, strlen(source), &options, aligned(&scratch),
                            sizeof scratch.bytes - 16, aligned(image), sizeof image->bytes - 16,
                            &info, NULL) == TLV_OK);
    *p = aligned(image);
    return 0;
}
static int export_plans(void) {
    const char* sources[] = {"//01",        "/70[child::01]", "(//01)[last()]", "//01/preceding::*",
                             "count(//01)", "exists(//01)",   "value(//01[1])"};
    puts("// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Marek Cingel\n"
         "// Generated by test-query-adversarial --export; source text deliberately omitted.\n"
         "// clang-format off");
    for (size_t i = 0; i < sizeof sources / sizeof *sources; ++i) {
        arena                      image;
        const tlv_query_program_t* p;
        CHECK(compile_plan(sources[i], NULL, &image, &p) == 0);
        tlv_query_plan_t header = *p;
        header.text_size = 0;
        header.reserved = header.text_offset + 1 + header.payload_size;
        printf("static const struct { tlv_query_plan_t header; tlv_query_instruction_t nodes[%u]; "
               "char source[1]; uint8_t payload[%u]; } native_%zu = {\n{",
               header.count, header.payload_size ? header.payload_size : 1, i);
        uint32_t fields[sizeof header / sizeof(uint32_t)];
        memcpy(fields, &header, sizeof header);
        for (size_t j = 0; j < sizeof fields / sizeof *fields; ++j)
            printf("%s%uu", j ? "," : "", fields[j]);
        puts("}, {");
        for (size_t n = 0; n < header.count; ++n) {
            uint32_t instruction[sizeof(tlv_query_instruction_t) / sizeof(uint32_t)];
            memcpy(instruction, (const uint8_t*)(p + 1) + n * sizeof instruction,
                   sizeof instruction);
            putchar('{');
            for (size_t j = 0; j < sizeof instruction / sizeof *instruction; ++j)
                printf("%s%uu", j ? "," : "", instruction[j]);
            puts("},");
        }
        printf("}, {0}, {");
        const uint8_t* payload = (const uint8_t*)p + p->text_offset + p->text_size + 1;
        for (size_t j = 0; j < header.payload_size; ++j) printf("%s%u", j ? "," : "", payload[j]);
        if (!header.payload_size) putchar('0');
        puts("}};");
    }
    puts("static const tlv_query_program_t* const native_plans[] = {"
         "&native_0.header, &native_1.header, &native_2.header, &native_3.header,"
         "&native_4.header, &native_5.header, &native_6.header};\n// clang-format on");
    return 0;
}
static int loader_aliases(void) {
    arena                      image, memory, before;
    const tlv_query_program_t* p;
    CHECK(compile_plan("//01", NULL, &image, &p) == 0);
    size_t bytes, alignment;
    CHECK(tlv_query_program_load_scratch(p, p->reserved, NULL, &bytes, &alignment, NULL) == TLV_OK);
    CHECK(bytes < 32768);
    const ptrdiff_t offsets[] = {0,
                                 1,
                                 -1,
                                 16,
                                 -16,
                                 (ptrdiff_t)p->reserved - 1,
                                 (ptrdiff_t)p->reserved,
                                 -(ptrdiff_t)bytes + 1,
                                 -(ptrdiff_t)bytes};
    for (size_t i = 0; i < sizeof offsets / sizeof *offsets; ++i) {
        memset(&memory, 0xa5, sizeof memory);
        uint8_t* copy = (uint8_t*)aligned(&memory) + 32768;
        memcpy(copy, p, p->reserved);
        uint8_t* scratch = copy + offsets[i];
        memcpy(&before, &memory, sizeof memory);
        const tlv_query_program_t* result = NULL;
        int                        overlap =
            offsets[i] >= 0 ? (size_t)offsets[i] < p->reserved : (size_t)-offsets[i] < bytes;
        int          invalid = overlap || (uintptr_t)scratch % alignment;
        tlv_result_t rc =
            tlv_query_program_load(copy, p->reserved, NULL, scratch, bytes, &result, NULL, NULL);
        CHECK(rc == (invalid ? TLV_ERR_INVALID_ARG : TLV_OK));
        if (invalid)
            CHECK(!result && !memcmp(&before, &memory, sizeof memory));
        else
            CHECK(result == (const tlv_query_program_t*)copy);
    }
    memset(&memory, 0xa5, sizeof memory);
    memcpy(&before, &memory, sizeof memory);
    tlv_query_program_info_t info = {0};
    info.struct_size = sizeof info;
    CHECK(tlv_query_compile("//01", 4, NULL, aligned(&memory), sizeof memory.bytes - 16,
                            aligned(&memory), 1024, &info, NULL) == TLV_ERR_INVALID_ARG);
    CHECK(!memcmp(&before, &memory, sizeof memory));
    size_t needed = 77;
    CHECK(tlv_query_compile_scratch("//01", 4, NULL, &needed, &needed, NULL) ==
          TLV_ERR_INVALID_ARG);
    CHECK(needed == 77);
    uint8_t immutable[2048];
    CHECK(p->reserved <= sizeof immutable);
    memcpy(immutable, p, p->reserved);
    CHECK(tlv_query_program_format(p, (char*)p, p->reserved, &needed) == TLV_ERR_INVALID_ARG);
    CHECK(!memcmp(immutable, p, p->reserved));
    return 0;
}
static void reenter(callback_state* s) {
    tlv_tree_event_t   input = event(), out;
    tlv_query_result_t result;
    int                matched = 123;
    ++s->calls;
    if (tlv_query_exec_feed(s->exec, &input, &matched, NULL) != TLV_ERR_INVALID_ARG ||
        matched != 123)
        ++s->errors;
    if (tlv_query_exec_finish(s->exec, NULL) != TLV_ERR_INVALID_ARG) ++s->errors;
    if (tlv_query_exec_reset(s->exec) != TLV_ERR_INVALID_ARG) ++s->errors;
    if (tlv_query_exec_bind(s->exec, "n", TLV_QUERY_RESULT_INTEGER, 1, NULL, 0, NULL) !=
        TLV_ERR_INVALID_ARG)
        ++s->errors;
    if (tlv_query_exec_context(s->exec, 0) != TLV_ERR_INVALID_ARG) ++s->errors;
    if (tlv_query_exec_pruning(s->exec, 1) != TLV_ERR_INVALID_ARG) ++s->errors;
    if (tlv_query_exec_result(s->exec, &result) != TLV_ERR_INVALID_ARG) ++s->errors;
    if (tlv_query_exec_selected(s->exec, &out) != TLV_ERR_INVALID_ARG) ++s->errors;
    if (tlv_query_result_next(s->exec, &out) != TLV_ERR_INVALID_ARG) ++s->errors;
}
static tlv_result_t resolve(const void* context, const char* ns, size_t ns_size, const char* name,
                            size_t size, tlv_tag_t* tag) {
    callback_state*      s = (callback_state*)context;
    static const uint8_t byte = 1;
    (void)ns;
    (void)ns_size;
    (void)name;
    (void)size;
    reenter(s);
    if (s->fail) return TLV_ERR_INVALID_TAG;
    *tag = tlv_tag(&byte, 1);
    return TLV_OK;
}
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
static tlv_visit_result_t document_visitor(tlv_node_t*, void*);
static void               mutate(callback_state* s) {
    if (!s->document) return;
    tlv_node_t*   node = s->node;
    tlv_node_t*   parent = tlv_node_parent(node);
    const uint8_t tag = 1, value = 8;
    uint64_t      identity = tlv_node_identity(node);
    switch (s->mutation) {
        case 1: tlv_node_erase(node); break;
        case 2: tlv_node_erase(parent ? parent : node); break;
        case 3:
        case 4:
            if (tlv_node_set_value(s->mutation == 4 && parent ? parent : node, &value, 1) !=
                TLV_ERR_INVALID_ARG)
                ++s->errors;
            break;
        case 5:
        case 6:
            if (tlv_document_insert(s->document, parent,
                                    s->mutation == 5 ? node : tlv_node_next(node), tlv_tag(&tag, 1),
                                    &value, 1, NULL) != TLV_ERR_INVALID_ARG)
                ++s->errors;
            break;
        case 7:
            if (tlv_document_query_program_visit(s->exec, document_visitor, s) !=
                TLV_ERR_INVALID_ARG)
                ++s->errors;
            break;
        case 8: tlv_document_free(s->document); break;
        case 9:
            tlv_node_erase(node);
            tlv_node_erase(parent ? parent : node);
            break;
    }
    /* Erase/free are deferred: borrowed node/tag/value survive this callback. */
    if (tlv_node_identity(node) != identity || tlv_node_tag(node).size != 1) ++s->errors;
}
static tlv_visit_result_t document_visitor(tlv_node_t* node, void* context) {
    callback_state* s = context;
    s->node = node;
    reenter(s);
    mutate(s);
    return TLV_VISIT_STOP;
}
#else
static void mutate(callback_state* s) {
    (void)s;
}
#endif
static tlv_codec_result_t decode(const void* context, const tlv_tree_event_t* input,
                                 const uint8_t* data, size_t size, void* scratch, size_t capacity,
                                 tlv_query_result_t* out) {
    callback_state* s = (callback_state*)context;
    (void)input;
    (void)data;
    (void)size;
    (void)scratch;
    (void)capacity;
    reenter(s);
    mutate(s);
    /* Resolver runs at compile time. Nested independent compilation is supported,
     * but operations on the surrounding active execution still must be rejected. */
    arena                       image, workspace;
    tlv_query_environment_t     environment = {0};
    tlv_query_compile_options_t options;
    tlv_query_compile_options_init(&options);
    options.environment = &environment;
    options.resolve = resolve;
    options.resolve_context = s;
    tlv_query_program_info_t info = {0};
    info.struct_size = sizeof info;
    tlv_result_t rc =
        tlv_query_compile("//named", 7, &options, aligned(&workspace), sizeof workspace.bytes - 16,
                          aligned(&image), sizeof image.bytes - 16, &info, NULL);
    if ((s->fail && rc == TLV_OK) || (!s->fail && rc != TLV_OK)) ++s->errors;
    out->kind = TLV_QUERY_RESULT_INTEGER;
    out->integer = 1;
    return s->fail ? TLV_CODEC_ERR_INVALID_VALUE : TLV_CODEC_OK;
}
static tlv_result_t tag_number(const void* context, const tlv_tag_t* tag, int64_t* out) {
    callback_state* s = (callback_state*)context;
    reenter(s);
    mutate(s);
    *out = tag->data[0];
    return s->fail ? TLV_ERR_INVALID_TAG : TLV_OK;
}
#if OPENTLV_READER
static tlv_visit_result_t event_visitor(const tlv_tree_event_t* input, void* context) {
    (void)input;
    reenter(context);
    return TLV_VISIT_CONTINUE;
}
#endif
static int callbacks(void) {
    tlv_fixed_format_t config = {0};
    config.tag_size = config.length_size = 1;
    config.length_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &config) == TLV_OK);
    callback_state          state = {0};
    tlv_query_hook_t        hook = {73, TLV_QUERY_NUM, 0, 1, &state, decode};
    tlv_query_tag_adapter_t tags = {74, &state, tag_number, tag_number};
    tlv_query_environment_t environment = {0};
    environment.hooks = &hook;
    environment.hook_count = 1;
    environment.tags = &tags;
    arena                      image, memory;
    const tlv_query_program_t* p;
    const char*                expressions[] = {"num(//01)", "number(//01)", "class(//01)"};
    for (unsigned kind = 0; kind < 3; ++kind) {
        CHECK(compile_plan(expressions[kind], &environment, &image, &p) == 0);
        size_t bytes, alignment;
        CHECK(tlv_query_eval_size(p, 2, 3, &bytes, &alignment) == TLV_OK);
        CHECK(tlv_query_eval_init(p, &environment, aligned(&memory), bytes, 2, 3, 100000,
                                  &state.exec) == TLV_OK);
        for (int failed = 1; failed >= 0; --failed) {
            state.fail = failed;
            state.calls = state.errors = 0;
            CHECK(tlv_query_exec_reset(state.exec) == TLV_OK);
            tlv_tree_event_t input = event();
            int              matched;
            CHECK(tlv_query_exec_feed(state.exec, &input, &matched, NULL) == TLV_OK);
            tlv_result_t rc = tlv_query_exec_finish(state.exec, NULL);
            CHECK(failed ? rc != TLV_OK : rc == TLV_OK);
            CHECK(state.calls && !state.errors);
            tlv_query_result_t result;
            CHECK(tlv_query_exec_result(state.exec, &result) ==
                  (failed ? TLV_ERR_INVALID_ARG : TLV_OK));
            if (!failed) CHECK(result.integer == 1);
        }
    }
#if OPENTLV_READER
    CHECK(compile_plan("//01", NULL, &image, &p) == 0);
    for (int retained = 0; retained < 2; ++retained) {
        size_t bytes;
        CHECK(initialize(p, retained, &memory, &state.exec, &bytes) == 0);
        const uint8_t     wire[] = {1, 0, 1, 0};
        tlv_tree_reader_t reader;
        tlv_tree_frame_t  frames[4];
        CHECK(tlv_tree_reader_init(&reader, wire, sizeof wire, &format, frames, 4, 3, 3) == TLV_OK);
        state.calls = state.errors = 0;
        CHECK(tlv_query_program_visit(&reader, state.exec, event_visitor, &state, NULL) == TLV_OK);
        CHECK(state.calls == 2 && !state.errors);
    }
#endif
    return 0;
}
#if OPENTLV_DOCUMENT && OPENTLV_READER && OPENTLV_WRITER
static int constructed(const void* context, const tlv_tag_t* tag) {
    (void)context;
    return tag->size == 1 && tag->data[0] == 0x70;
}
static int documents(void) {
    const char*        expressions[] = {"//01",           "/70[child::01]",
                                        "(//01)[last()]", "//01 | //01/following::*",
                                        "num(//01[1])",   "number(//01[1])"};
    tlv_fixed_format_t config = {0};
    config.tag_size = config.length_size = 1;
    config.length_order = TLV_BYTE_ORDER_BIG_ENDIAN;
    tlv_format_t format;
    CHECK(tlv_fixed_format_init(&format, &config) == TLV_OK);
    format.is_constructed = constructed;
    tlv_document_options_t options;
    CHECK(tlv_document_options_init(&options, &format) == TLV_OK);
    options.retain_source_locations = 1;
    for (unsigned kind = 0; kind < 6; ++kind)
        for (int mutation = 0; mutation <= 9; ++mutation) {
            const uint8_t  wire[] = {0x70, 3, 1, 1, 9};
            callback_state state = {0};
            state.mutation = mutation;
            CHECK(tlv_document_parse(wire, sizeof wire, &options, &state.document, NULL) == TLV_OK);
            state.node = tlv_node_first_child(tlv_document_first(state.document));
            tlv_query_hook_t        hook = {73, TLV_QUERY_NUM, 0, 1, &state, decode};
            tlv_query_tag_adapter_t tags = {74, &state, tag_number, tag_number};
            tlv_query_environment_t environment = {0};
            environment.format = &format;
            environment.hooks = &hook;
            environment.hook_count = 1;
            environment.tags = &tags;
            arena                      image, memory;
            const tlv_query_program_t* p;
            CHECK(compile_plan(expressions[kind], &environment, &image, &p) == 0);
            size_t bytes, alignment;
            CHECK(tlv_query_eval_size(p, 3, 8, &bytes, &alignment) == TLV_OK);
            CHECK(tlv_query_eval_init(p, &environment, aligned(&memory), bytes, 3, 8, 100000,
                                      &state.exec) == TLV_OK);
            uint8_t                     values[64], scratch[64];
            tlv_tree_writer_frame_t     frames[8];
            tlv_tree_writer_workspace_t staging = {0};
            staging.data = values;
            staging.data_capacity = sizeof values;
            staging.scratch = scratch;
            staging.scratch_capacity = sizeof scratch;
            staging.frames = frames;
            staging.frame_capacity = 8;
            tlv_result_t rc = tlv_document_query_evaluate(state.document, state.exec, NULL, values,
                                                          sizeof values, &staging, NULL);
            if (kind < 4) {
                CHECK(rc == TLV_OK);
                rc = tlv_document_query_program_visit(state.exec, document_visitor, &state);
            }
            int invalid = mutation == 1 || mutation == 2 || mutation == 8 || mutation == 9;
            CHECK(rc == (invalid ? TLV_ERR_INVALID_ARG : TLV_OK));
            CHECK(state.calls && !state.errors);
            if (invalid) {
                tlv_query_result_t output;
                tlv_node_t*        node = NULL;
                CHECK(tlv_query_exec_result(state.exec, &output) == TLV_ERR_INVALID_ARG);
                CHECK(tlv_document_query_next(state.exec, &node) == TLV_ERR_INVALID_ARG);
            }
            CHECK(tlv_query_exec_reset(state.exec) == TLV_OK);
            if (mutation != 8) tlv_document_free(state.document);
        }
    return 0;
}
#endif
#endif
