# Compile-time guarantees remain testable when the runtime frontend is disabled.
function(opentlv_check_constexpr_query)
    include(CheckCXXSourceCompiles)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_REQUIRED_INCLUDES
        "${OpenTLV_SOURCE_DIR}/tlv/include"
        "${OpenTLV_SOURCE_DIR}/tlv++/include"
        "${OpenTLV_BINARY_DIR}/generated/include")
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/W4 /WX /EHsc")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c++11 -Wall -Wextra -Wpedantic -Werror")
    endif()
    set(valid "constexpr auto p = q::where(q::child<1>(), q::length() == q::parameter(\"n\")).compile(); static_assert(p.header().count == 7, \"native absolute-path instructions\");")
    set(bad_name "constexpr auto p = q::parameter(\"9bad\").compile();")
    set(conflicting_types "constexpr auto p = q::where(q::child<1>(), (q::length() == q::parameter(\"x\")) && (q::value() == q::parameter<TLV_QUERY_PLAN_BYTES>(\"x\"))).compile();")
    set(temporary_borrow "auto p = q::child<1>().compile().program();")
    foreach(case IN ITEMS valid bad_name conflicting_types temporary_borrow)
        set(result "OPENTLV_CONSTEXPR_QUERY_${case}")
        unset(${result} CACHE)
        check_cxx_source_compiles("#include <tlv++/query/static.hpp>\nnamespace q = tlv::static_query;\n${${case}}\nint main() {}" ${result}
            OUTPUT_VARIABLE compile_output)
        if(case STREQUAL "valid" AND NOT ${result})
            message(FATAL_ERROR "Valid constexpr Query must compile:\n${compile_output}")
        elseif(NOT case STREQUAL "valid" AND ${result})
            message(FATAL_ERROR "Invalid constexpr Query ${case} must fail to compile")
        endif()
    endforeach()
endfunction()
opentlv_check_constexpr_query()
