#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Marek Cingel
"""Emit independently authored source-free C plans and matching constexpr cases."""
from pathlib import Path
import argparse


def generate():
    c = ['// SPDX-License-Identifier: MIT', '// Copyright (c) 2026 Marek Cingel',
         '// Generated by generate_adversarial_plans.py; do not edit.', '// clang-format off',
         '#include "tlv/query/plan.h"',
         '#define N TLV_QUERY_PLAN_NONE',
         '#define BASE(L,R,P) .left=L, .right=R, .predicate_guard=P, .path_guard=N, .reuse=N',
         'struct generated_image { tlv_query_plan_t h; tlv_query_instruction_t n[7]; char text[1]; uint8_t payload[2]; };']
    cases = ['// SPDX-License-Identifier: MIT', '// Copyright (c) 2026 Marek Cingel', '// Generated by generate_adversarial_plans.py; do not edit.', '// clang-format off']
    index = 0
    for tag in (1, 2, 3):
        for axis in ('child', 'descendant'):
            for operator, op in (('==', 'EQ'), ('!=', 'NE'), ('<', 'LT'), ('>=', 'GE')):
                for operand in ('0', '2', '$n'):
                    variable = operand == '$n'
                    right = ('{BASE(N,N,1), .op=TLV_QUERY_OP_VARIABLE, .type=TLV_QUERY_PLAN_INTEGER, .low=3, '
                             '.data_offset=1, .data_size=1}' if variable else
                             '{BASE(N,N,1), .op=TLV_QUERY_OP_LITERAL, .type=TLV_QUERY_PLAN_INTEGER, .low=3, '
                             f'.immediate_low={operand}}}')
                    c += [f'static const struct generated_image image_{index} = {{',
                          '.h={.magic=TLV_QUERY_PLAN_MAGIC, .version=TLV_QUERY_PLAN_VERSION, .count=7, .root=6,',
                          '.text_offset=sizeof(tlv_query_plan_t)+7*sizeof(tlv_query_instruction_t),',
                          '.reserved=sizeof(tlv_query_plan_t)+7*sizeof(tlv_query_instruction_t)+3,',
                          f'.payload_size=2, .variable_count={int(variable)}}},',
                          '.n={{BASE(N,N,N), .op=TLV_QUERY_OP_ROOT},',
                          '{.left=N, .right=N, .predicate_guard=N, .reuse=N, .path_guard=0, .low=1, .op=TLV_QUERY_OP_TEST, .resolved=1, .data_size=1,',
                          f'.path_kind=TLV_QUERY_OP_{"CHILD" if axis == "child" else "DESC"},',
                          f'.axis=TLV_QUERY_AXIS_{"CHILD" if axis == "child" else "DESC"}}},',
                          '{BASE(N,N,1), .op=TLV_QUERY_OP_META, .type=TLV_QUERY_PLAN_INTEGER, .low=2},',
                          right + ',',
                          f'{{BASE(2,3,1), .op=TLV_QUERY_OP_{op}, .low=2, .type=TLV_QUERY_PLAN_BOOL}},',
                          '{BASE(1,4,N), .op=TLV_QUERY_OP_FILTER, .low=1},',
                          '{BASE(0,5,N), .op=TLV_QUERY_OP_CHILD}},',
                          f'.payload={{{tag}, {ord("n") if variable else 0}}}}};']
                    source = f'{"/" if axis == "child" else "//"}{tag:02X}[@len {"=" if operator == "==" else operator} {operand}]'
                    expr = f'q::where(q::{axis}<{tag}>(), q::length() {operator} '
                    expr += 'q::parameter("n"))' if variable else f'q::integer({operand}))'
                    cases.append(f'CASE({index}, {expr}, "{source}")')
                    index += 1
    for value in (0, 1, -1, 9223372036854775807, -9223372036854775808):
        magnitude = abs(value)
        c += [f'static const struct {{ tlv_query_plan_t h; tlv_query_instruction_t n[3]; char text[1]; }} image_{index} = {{',
              '.h={.magic=TLV_QUERY_PLAN_MAGIC, .version=TLV_QUERY_PLAN_VERSION, .count=3, .root=2,',
              '.level=TLV_QUERY_S2, .text_offset=sizeof(tlv_query_plan_t)+3*sizeof(tlv_query_instruction_t),',
              '.reserved=sizeof(tlv_query_plan_t)+3*sizeof(tlv_query_instruction_t)+1},',
              '.n={{BASE(N,N,N), .op=TLV_QUERY_OP_LITERAL, .type=TLV_QUERY_PLAN_INTEGER,',
              f'.immediate_low={magnitude & 0xffffffff}u, .immediate_high={magnitude >> 32}u, .negative={int(value < 0)}}},',
              '{BASE(N,N,N), .op=TLV_QUERY_OP_LITERAL, .type=TLV_QUERY_PLAN_INTEGER, .low=1},',
              '{BASE(0,1,N), .op=TLV_QUERY_OP_GE, .type=TLV_QUERY_PLAN_BOOL}}};']
        literal = 'INT64_MIN' if value == -9223372036854775808 else f'INT64_C({value})'
        cases.append(f'CASE({index}, q::integer({literal}) >= q::integer(0), "{value} >= 0")')
        index += 1
    c += ['const tlv_query_program_t* query_generated_plan(unsigned index) {', 'switch(index) {']
    c += [f'case {i}: return &image_{i}.h;' for i in range(index)]
    c += ['default: return 0;', '}}', '#undef BASE', '#undef N', '// clang-format on', '']
    return {'adversarial_generated.c': '\n'.join(c), 'adversarial_cases.inc': '\n'.join(cases + ['// clang-format on']) + '\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in generate().items():
        path = Path(__file__).with_name(name)
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Stale generated fixture: {path}')
        else:
            path.write_text(content)
