# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Marek Cingel

"""Typed C diagnostic categories; unknown values keep their numeric identity.

Generated by scripts/generate_diagnostic_vocabulary.py; do not edit.
"""
from enum import IntEnum
import _opentlv as _native

_INT_MIN, _INT_MAX = -(2 ** 31), 2 ** 31 - 1
_FAMILIES = {
    "ReaderOperation": "reader_operation",
    "WriterOperation": "writer_operation",
    "QueryErrorKind": "query_error_kind",
    "QueryCause": "query_cause",
    "SchemaIssue": "schema_issue_kind",
    "SchemaDefinitionKind": "schema_definition_kind",
    "CodecOperation": "codec_operation",
    "CodecCause": "codec_cause",
    "CodecViolation": "codec_violation",
    "Severity": "diagnostic_severity",
}


class _Category(IntEnum):
    @classmethod
    def _missing_(cls, value):
        if not isinstance(value, int):
            return None
        # Cache the pseudo-member so equal unknown values stay identical.
        item = int.__new__(cls, value)
        item._name_ = f"UNKNOWN_{value}"
        item._value_ = value
        return cls._value2member_map_.setdefault(value, item)

    @property
    def label(self):
        """Canonical C spelling; "unknown" for unrecognized values."""
        if not _INT_MIN <= self.value <= _INT_MAX:
            return "unknown"
        return _native.diagnostic_name(_FAMILIES[type(self).__name__], self.value)


class ReaderOperation(_Category):
    """Canonical ReaderOperation category."""
    TAG = 0
    LENGTH = 1
    VALUE = 2
    TRAILER = 3
    HEADER = 4


class WriterOperation(_Category):
    """Canonical WriterOperation category."""
    TAG = 0
    LENGTH = 1
    VALUE = 2
    HEADER = 3
    TRAILER = 4
    COPY = 5
    PRESERVE = 6
    BEGIN = 7
    END = 8


class QueryErrorKind(_Category):
    """Canonical QueryErrorKind category."""
    NONE = 0
    SYNTAX = 1
    CAPABILITY = 2
    LIMIT = 3
    STORAGE = 4
    EVENTS = 5
    SOURCE = 6
    READER = 7
    BINDING = 8
    CARDINALITY = 9
    CODEC = 10
    IMAGE_VERSION = 11
    STATE = 12
    CALLBACK = 13
    TYPE = 14
    IMAGE = 15
    SCHEMA = 16


class QueryCause(_Category):
    """Canonical QueryCause category."""
    NONE = 0
    READER = 1
    CODEC = 2
    SCHEMA = 3


class SchemaIssue(_Category):
    """Canonical SchemaIssue category."""
    NONE = 0
    MISSING = 1
    DUPLICATE = 2
    UNEXPECTED = 3
    KIND = 4
    LENGTH = 5
    ORDER = 6
    ASSERTION = 7
    VALUE = 8
    DEFINITION = 9


class SchemaDefinitionKind(_Category):
    """Canonical SchemaDefinitionKind category."""
    UNKNOWN = 0
    TABLE = 1
    RULE = 2
    GROUP = 3
    TYPE = 4
    COMPONENT = 5


class CodecOperation(_Category):
    """Canonical CodecOperation category."""
    DECODE = 0
    ENCODE = 1
    MEASURE = 2


class CodecCause(_Category):
    """Canonical CodecCause category."""
    NONE = 0
    READER = 1
    SCHEMA = 2


class CodecViolation(_Category):
    """Canonical CodecViolation category."""
    NONE = 0
    RESULT = 1
    SIZE = 2
    TYPE = 3
    UTF8 = 4


class Severity(_Category):
    """Canonical Severity category."""
    ERROR = 0
    WARNING = 1
    INFO = 2
