# Positive controls and invalid contracts compile with the C++11 public headers.
function(opentlv_check_custom_format)
    if(NOT OPENTLV_BUILD_CXX)
        return()
    endif()
    include(CheckCXXSourceCompiles)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_REQUIRED_INCLUDES
        "${OpenTLV_SOURCE_DIR}/tlv/include"
        "${OpenTLV_SOURCE_DIR}/tlv++/include"
        "${OpenTLV_SOURCE_DIR}/tests"
        "${OpenTLV_BINARY_DIR}/generated/include")
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/W4 /WX /EHsc")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c++11 -Wall -Wextra -Werror")
    endif()
    set(header "#include <custom_cpp_format.hpp>\n#include <tlv++/reader/reader.hpp>\n#include <tlv++/writer/writer.hpp>\n")
    set(cases valid empty missing_encode wrong_decode throwing_decode nonconst_decode wrong_classifier wrong_measure wrong_encode reader_write_only writer_read_only)
    set(valid "using F = custom_cpp_format")
    set(empty "struct F {}")
    set(missing_encode "struct F { tlv::expected<tlv::encoding, tlv::format_failure> measure(const tlv::measure_request&) const noexcept; }")
    set(wrong_decode "struct F : custom_cpp_format { int decode(tlv::bytes) const noexcept; }")
    set(throwing_decode "struct F : custom_cpp_format { tlv::expected<tlv::decoded, tlv::format_failure> decode(tlv::bytes) const; }")
    set(nonconst_decode "struct F : custom_cpp_format { tlv::expected<tlv::decoded, tlv::format_failure> decode(tlv::bytes) noexcept; }")
    set(wrong_classifier "struct F : custom_cpp_format { int is_constructed(tlv::tag) const noexcept; }")
    set(wrong_measure "struct F : custom_cpp_format { int measure(const tlv::measure_request&) const noexcept; }")
    set(wrong_encode "struct F : custom_cpp_format { int encode(const tlv::element_view&, tlv::span<tlv::byte>) const noexcept; }")
    set(reader_write_only "struct F { tlv::expected<tlv::encoding, tlv::format_failure> measure(const tlv::measure_request&) const noexcept; tlv::expected<size_t, tlv::format_failure> encode(const tlv::element_view&, tlv::span<tlv::byte>) const noexcept; }")
    set(writer_read_only "struct F { tlv::expected<tlv::decoded, tlv::format_failure> decode(tlv::bytes) const noexcept; }")
    foreach(case IN LISTS cases)
        set(body "tlv::format_adapter<F> adapter; (void)adapter")
        if(case STREQUAL "reader_write_only")
            set(body "tlv::reader<F> reader(tlv::bytes{}); (void)reader")
        elseif(case STREQUAL "writer_read_only")
            set(body "tlv::writer<F> writer(nullptr, 0); (void)writer")
        endif()
        set(result "OPENTLV_CUSTOM_FORMAT_${case}")
        unset(${result} CACHE)
        check_cxx_source_compiles("${header}\n${${case}};\nint main() { ${body}; }" ${result})
        if(case STREQUAL "valid" AND NOT ${result})
            message(FATAL_ERROR "Valid C++ Format contract must compile")
        elseif(NOT case STREQUAL "valid" AND ${result})
            message(FATAL_ERROR "Invalid C++ Format contract ${case} must fail to compile")
        endif()
    endforeach()
endfunction()
opentlv_check_custom_format()
