# Verify public borrowing and exception policy, with a positive control per header set.
function(opentlv_check_cxx_contracts)
    if(NOT OPENTLV_BUILD_CXX)
        return()
    endif()
    include(CheckCXXSourceCompiles)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_REQUIRED_INCLUDES
        "${OpenTLV_SOURCE_DIR}/tlv/include"
        "${OpenTLV_SOURCE_DIR}/tlv++/include"
        "${OpenTLV_BINARY_DIR}/generated/include")
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/W4 /WX /EHsc")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c++11 -Wall -Wextra -Werror")
    endif()
    set(header "#include <tlv++/formats/runtime_fixed.hpp>\n#include <tlv++/schema/definition.hpp>\n#include <tlv++/query/options.hpp>\n#include <tlv++/writer/builder.hpp>\n")
    set(valid "tlv::runtime_fixed_format f(1, 1); auto v = f.view(); tlv::schema_storage<0> s({}); auto sv = s.view(); tlv::query_options q; auto qv = q.view(); tlv::writer_storage<4> w; auto wv = w.view(); (void)v; (void)sv; (void)qv; (void)wv;")
    set(format_temporary "auto v = tlv::runtime_fixed_format(1, 1).view(); (void)v;")
    set(schema_temporary "auto v = tlv::schema_storage<0>({}).view(); (void)v;")
    set(query_temporary "auto v = tlv::query_options().view(); (void)v;")
    set(workspace_temporary "auto v = tlv::writer_storage<4>().view(); (void)v;")
    foreach(case IN ITEMS valid format_temporary schema_temporary query_temporary workspace_temporary)
        set(result "OPENTLV_CXX_CONTRACT_${case}")
        unset(${result} CACHE)
        check_cxx_source_compiles("${header}\nint main() { ${${case}} }" ${result})
        if(case STREQUAL "valid" AND NOT ${result})
            message(FATAL_ERROR "Public C++ borrowing positive control must compile")
        elseif(NOT case STREQUAL "valid" AND ${result})
            message(FATAL_ERROR "Temporary borrowing ${case} must fail to compile")
        endif()
    endforeach()
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/EHs-c-")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c++11 -fno-exceptions")
    endif()
    unset(OPENTLV_CXX_WITHOUT_EXCEPTIONS CACHE)
    check_cxx_source_compiles("#include <tlv++/compat.hpp>\nint main() {}" OPENTLV_CXX_WITHOUT_EXCEPTIONS)
    if(OPENTLV_CXX_WITHOUT_EXCEPTIONS)
        message(FATAL_ERROR "tlv++ must explicitly reject exception-disabled compilation")
    endif()
endfunction()
opentlv_check_cxx_contracts()
