# Field Encoding must compile on its own in C99 and C++11, including when
# Format and Format Composition headers are unavailable through transitive includes.
function(opentlv_check_field_encoding)
    include(CheckCSourceCompiles)
    include(CheckCXXSourceCompiles)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_C_STANDARD 99)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(isolated "${CMAKE_CURRENT_BINARY_DIR}/field-encoding/include")
    file(GLOB_RECURSE headers CONFIGURE_DEPENDS
         RELATIVE "${OpenTLV_SOURCE_DIR}/tlv/include"
         "${OpenTLV_SOURCE_DIR}/tlv/include/*.h")
    foreach(header IN LISTS headers)
        if(header STREQUAL "tlv/format.h" OR header MATCHES "^tlv/formats/")
            get_filename_component(directory "${isolated}/${header}" DIRECTORY)
            file(MAKE_DIRECTORY "${directory}")
            file(WRITE "${isolated}/${header}"
                 "#error Field Encoding must not depend on Format or Format Composition\n")
        else()
            configure_file("${OpenTLV_SOURCE_DIR}/tlv/include/${header}"
                           "${isolated}/${header}" COPYONLY)
        endif()
    endforeach()
    set(CMAKE_REQUIRED_INCLUDES "${isolated}" "${OpenTLV_BINARY_DIR}/generated/include")
    foreach(language IN ITEMS C CXX)
        foreach(header IN ITEMS encoding packed variable escaped)
            set(result "OPENTLV_FIELD_ENCODING_${language}_${header}")
            unset(${result} CACHE)
            set(source "#include <tlv/field/${header}.h>\nint field_header_check(void) { return 0; }\n")
            if(language STREQUAL "C")
                check_c_source_compiles("${source}" ${result})
            else()
                check_cxx_source_compiles("${source}" ${result})
            endif()
            if(NOT ${result})
                message(FATAL_ERROR "tlv/field/${header}.h must compile in ${language} without Format")
            endif()
        endforeach()
        # Confirm that an accidental dependency cannot pass through the include search path.
        set(result "OPENTLV_FIELD_ENCODING_${language}_forbidden_format")
        unset(${result} CACHE)
        set(source "#include <tlv/formats/compose.h>\nint forbidden_format_check(void) { return 0; }\n")
        if(language STREQUAL "C")
            check_c_source_compiles("${source}" ${result})
        else()
            check_cxx_source_compiles("${source}" ${result})
        endif()
        if(${result})
            message(FATAL_ERROR "Field Encoding isolation check did not exclude Format in ${language}")
        endif()
    endforeach()
endfunction()

opentlv_check_field_encoding()
