# Typed fields must reject invalid contracts with C++11-compatible diagnostics.
function(opentlv_check_typed_fields)
    if(NOT OPENTLV_BUILD_CXX)
        return()
    endif()
    include(CheckCXXSourceCompiles)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_REQUIRED_INCLUDES
        "${OpenTLV_SOURCE_DIR}/tlv/include"
        "${OpenTLV_SOURCE_DIR}/tlv++/include"
        "${OpenTLV_BINARY_DIR}/generated/include")
    if(MSVC)
        set(CMAKE_REQUIRED_FLAGS "/W4 /WX /EHsc")
    else()
        set(CMAKE_REQUIRED_FLAGS "-std=c++11 -Wall -Wextra -Werror")
    endif()
    set(valid "using C = tlv::uint8_codec; using T = uint8_t;")
    set(wrong_type "using C = tlv::uint8_codec; using T = uint16_t;")
    set(missing_encode "struct C { using value_type = uint8_t; static tlv::expected<uint8_t, tlv_codec_result_t> decode(tlv::bytes); }; using T = uint8_t;")
    set(wrong_decode "struct C : tlv::uint8_codec { static int decode(tlv::bytes); }; using T = uint8_t;")
    set(no_default "using T = uint16_t; using C = tlv::codec<T>;")
    foreach(case IN ITEMS valid wrong_type missing_encode wrong_decode no_default)
        set(result "OPENTLV_TYPED_FIELD_${case}")
        unset(${result} CACHE)
        check_cxx_source_compiles("#include <tlv++/codec/typed.hpp>\n${${case}}\nusing F = tlv::field<tlv::tag_constant<0, 1>, T, C>;\nint main() { F field; (void)field; }" ${result})
        if(case STREQUAL "valid" AND NOT ${result})
            message(FATAL_ERROR "Valid typed field must compile")
        elseif(NOT case STREQUAL "valid" AND ${result})
            message(FATAL_ERROR "Invalid typed field ${case} must fail to compile")
        endif()
    endforeach()
endfunction()
opentlv_check_typed_fields()
