local opentlv = require("opentlv")

describe("opentlv.errors", function()
    it("mirrors every tlv_result_t code", function()
        assert(opentlv.errors.OK == 0)
        assert(opentlv.errors.BUFFER_TOO_SHORT == 1)
        assert(opentlv.errors.INVALID_LENGTH == 2)
        assert(opentlv.errors.NULL_ARG == 3)
        assert(opentlv.errors.OUT_OF_MEMORY == 4)
        assert(opentlv.errors.END_OF_BUFFER == 5)
        assert(opentlv.errors.INVALID_TAG == 6)
        assert(opentlv.errors.VISITOR == 7)
        assert(opentlv.errors.LIMIT == 8)
        assert(opentlv.errors.SCHEMA == 9)
        assert(opentlv.errors.INVALID_ARG == 10)
        assert(opentlv.errors.INVALID_TAG_SIZE == 11)
        assert(opentlv.errors.INVALID_BYTE_ORDER == 12)
        assert(opentlv.errors.OVERFLOW == 13)
        assert(opentlv.errors.INVALID_VALUE == 14)
        assert(opentlv.errors.UNSUPPORTED_TYPE == 15)
        assert(opentlv.errors.SCHEMA_MISSING == 16)
    end)
end)

describe("opentlv.strerror", function()
    it("describes a known code as a non-empty string", function()
        local message = opentlv.strerror(opentlv.errors.BUFFER_TOO_SHORT)
        assert(type(message) == "string")
        assert(#message > 0)
    end)

    it("describes an unrecognized code without raising", function()
        local message = opentlv.strerror(9999)
        assert(type(message) == "string")
    end)
end)

describe("opentlv.version", function()
    it("returns a non-empty string, also available as opentlv._VERSION", function()
        assert(type(opentlv.version()) == "string")
        assert(#opentlv.version() > 0)
        assert(opentlv._VERSION == opentlv.version())
    end)
end)

describe("error objects", function()
    it("format as a readable string via tostring()", function()
        local ok, err = pcall(function()
            for _ in opentlv.reader(string.char(0x01), opentlv.formats.ber) do
            end
        end)
        assert(not ok)
        local text = tostring(err)
        assert(text:find("opentlv:", 1, true) ~= nil)
        assert(text:find(tostring(err.code), 1, true) ~= nil)
    end)

    it("carry a message describing the code", function()
        local ok, err = pcall(function()
            for _ in opentlv.reader(string.char(0x01), opentlv.formats.ber) do
            end
        end)
        assert(not ok)
        assert(err.message == opentlv.strerror(err.code))
    end)
end)
