-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Marek Cingel
local tlv = require("opentlv")
local b = string.char
local f = tlv.formats.ber or tlv.formats.fixed(1, 1, "big")
local function fails(run, code)
    local ok, err = pcall(run)
    assert(not ok, "expected failure")
    if code then assert(type(err) == "table" and err.code == code, tostring(err)) end
    return err
end
local options = {variables = {min = "integer"}, optimize = true}
local p = tlv.query_program("count(//5A[@len >= $min])", f, options)
assert(p:info().variable_slots == 1 and p:variables().min == 2)
assert(#p:format() > 0 and #p:explain() > 0)
local loaded = tlv.query_program_load(p:image(), f, options)
fails(function() tlv.query_program_load(p:image():sub(1,-2), f, options) end)
local q = loaded:execution()
q:bind("min", "integer", 2)
q:set_input(b(0x5a,1,9,0x5a,2,8,7))
q:visit(function() error("scalar emitted node") end)
assert(q:result() == 1)
q:close()
fails(function() q:result() end, tlv.errors.INVALID_ARG)

local streaming = tlv.query_program("//5A", f):execution({retained = false})
streaming:set_input(b(0x5a,1,9),0,false)
local first = streaming:next()
assert(first.value == b(9) and first.offset == 0)
fails(function() streaming:next() end, tlv.errors.NEED_MORE_DATA)
collectgarbage("collect")
streaming:set_input(b(0x5a,1,9,0x5a,1,8),0,true)
streaming:visit(function(match)
    assert(match.offset == 3)
    fails(function() streaming:reset() end, tlv.errors.INVALID_ARG)
    fails(function() streaming:close() end, tlv.errors.INVALID_ARG)
    return false
end)
assert(streaming:next() == nil)
streaming:reset()
assert(first.value == b(9))
streaming:set_input(b(0x5a,0))
assert(fails(function() streaming:visit(function() error("callback failure") end) end):match("callback failure"))
fails(function() streaming:next() end, tlv.errors.INVALID_ARG)
streaming:reset()
streaming:set_input(b(0x5a,0,0x5a))
assert(streaming:exists(true))
assert(streaming:info().full_validation == 0)
streaming:reset()
streaming:set_input(b(0x5a,0,0x5a))
fails(function() streaming:exists(false) end, tlv.errors.BUFFER_TOO_SHORT)

local names = tlv.query_program("count(//fixture:leaf)",f,{names={["fixture:leaf"]=b(0x5a)}}):execution()
names:set_input(b(0x5a,0));names:visit(function() end);assert(names:result()==1)
local diagnostic = fails(function() tlv.query_program("//5A[", f) end)
assert(type(diagnostic.query) == "table" and type(diagnostic.query.begin)=="number")
if tlv.document and tlv.formats.ber then
    local doc = tlv.document(b(0x70,6,0x5a,1,1,0x5a,1,2),f)
    local selected = tlv.query_program("//5A/preceding-sibling::*",f):execution()
    selected:evaluate_document(doc)
    local node = selected:next()
    assert(node:value()==b(1) and node:identity()>0)
    node:set(b(7))
    fails(function() selected:next() end,tlv.errors.INVALID_ARG)
    selected:reset();selected:evaluate_document(doc)
    assert(selected:next():value()==b(7))
    selected:close()
    local scalar = tlv.query_program("value((//5A)[1])",f):execution()
    scalar:evaluate_document(doc)
    assert(scalar:result()==b(7))
end
print("Lua compiled Query lifetime, continuation, callbacks and Document tests passed")
