[package]
name = "opentlv"
description = "Safe Rust bindings for OpenTLV"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["lldp", "document", "nfc"]
lldp = ["opentlv-native/lldp"]
nfc = ["opentlv-native/nfc"]
document = ["opentlv-native/document"]

[dependencies]
opentlv-native = { path = "../opentlv-native", default-features = false }
