// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Marek Cingel
//! Generated by scripts/generate_diagnostic_vocabulary.py; do not edit.
use opentlv::{
    CodecCause, CodecOperation, CodecViolation, QueryErrorKind, ReaderOperation,
    SchemaDefinitionKind, SchemaIssue, Severity, WriterOperation,
};

#[test]
fn reader_operation_matches_native_vocabulary() {
    for (member, raw, name) in [
        (ReaderOperation::Tag, 0, "tag"),
        (ReaderOperation::Length, 1, "length"),
        (ReaderOperation::Value, 2, "value"),
        (ReaderOperation::Trailer, 3, "trailer"),
        (ReaderOperation::Header, 4, "header"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(ReaderOperation::from_raw(raw), member);
    }
    let beyond = ReaderOperation::from_raw(5);
    assert_eq!((beyond.as_raw(), beyond.name()), (5, "unknown"));
}

#[test]
fn writer_operation_matches_native_vocabulary() {
    for (member, raw, name) in [
        (WriterOperation::Tag, 0, "tag"),
        (WriterOperation::Length, 1, "length"),
        (WriterOperation::Value, 2, "value"),
        (WriterOperation::Header, 3, "header"),
        (WriterOperation::Trailer, 4, "trailer"),
        (WriterOperation::Copy, 5, "copy"),
        (WriterOperation::Preserve, 6, "preserve"),
        (WriterOperation::Begin, 7, "begin"),
        (WriterOperation::End, 8, "end"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(WriterOperation::from_raw(raw), member);
    }
    let beyond = WriterOperation::from_raw(9);
    assert_eq!((beyond.as_raw(), beyond.name()), (9, "unknown"));
}

#[test]
fn query_error_kind_matches_native_vocabulary() {
    for (member, raw, name) in [
        (QueryErrorKind::None, 0, "none"),
        (QueryErrorKind::Syntax, 1, "syntax"),
        (QueryErrorKind::Capability, 2, "capability"),
        (QueryErrorKind::Limit, 3, "limit"),
        (QueryErrorKind::Storage, 4, "storage"),
        (QueryErrorKind::Events, 5, "events"),
        (QueryErrorKind::Source, 6, "source"),
        (QueryErrorKind::Reader, 7, "reader"),
        (QueryErrorKind::Binding, 8, "binding"),
        (QueryErrorKind::Cardinality, 9, "cardinality"),
        (QueryErrorKind::Codec, 10, "codec"),
        (QueryErrorKind::ImageVersion, 11, "image_version"),
        (QueryErrorKind::State, 12, "state"),
        (QueryErrorKind::Callback, 13, "callback"),
        (QueryErrorKind::Type, 14, "type"),
        (QueryErrorKind::Image, 15, "image"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(QueryErrorKind::from_raw(raw), member);
    }
    let beyond = QueryErrorKind::from_raw(16);
    assert_eq!((beyond.as_raw(), beyond.name()), (16, "unknown"));
}

#[test]
fn schema_issue_matches_native_vocabulary() {
    for (member, raw, name) in [
        (SchemaIssue::None, 0, "none"),
        (SchemaIssue::Missing, 1, "missing"),
        (SchemaIssue::Duplicate, 2, "duplicate"),
        (SchemaIssue::Unexpected, 3, "unexpected"),
        (SchemaIssue::Kind, 4, "kind"),
        (SchemaIssue::Length, 5, "length"),
        (SchemaIssue::Order, 6, "order"),
        (SchemaIssue::Assertion, 7, "assertion"),
        (SchemaIssue::Value, 8, "value"),
        (SchemaIssue::Definition, 9, "definition"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(SchemaIssue::from_raw(raw), member);
    }
    let beyond = SchemaIssue::from_raw(10);
    assert_eq!((beyond.as_raw(), beyond.name()), (10, "unknown"));
}

#[test]
fn schema_definition_kind_matches_native_vocabulary() {
    for (member, raw, name) in [
        (SchemaDefinitionKind::Unknown, 0, "unknown"),
        (SchemaDefinitionKind::Table, 1, "table"),
        (SchemaDefinitionKind::Rule, 2, "rule"),
        (SchemaDefinitionKind::Group, 3, "group"),
        (SchemaDefinitionKind::Type, 4, "type"),
        (SchemaDefinitionKind::Component, 5, "component"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(SchemaDefinitionKind::from_raw(raw), member);
    }
    let beyond = SchemaDefinitionKind::from_raw(6);
    assert_eq!((beyond.as_raw(), beyond.name()), (6, "unknown"));
}

#[test]
fn codec_operation_matches_native_vocabulary() {
    for (member, raw, name) in [
        (CodecOperation::Decode, 0, "decode"),
        (CodecOperation::Encode, 1, "encode"),
        (CodecOperation::Measure, 2, "measure"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(CodecOperation::from_raw(raw), member);
    }
    let beyond = CodecOperation::from_raw(3);
    assert_eq!((beyond.as_raw(), beyond.name()), (3, "unknown"));
}

#[test]
fn codec_cause_matches_native_vocabulary() {
    for (member, raw, name) in [
        (CodecCause::None, 0, "none"),
        (CodecCause::Reader, 1, "reader"),
        (CodecCause::Schema, 2, "schema"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(CodecCause::from_raw(raw), member);
    }
    let beyond = CodecCause::from_raw(3);
    assert_eq!((beyond.as_raw(), beyond.name()), (3, "unknown"));
}

#[test]
fn codec_violation_matches_native_vocabulary() {
    for (member, raw, name) in [
        (CodecViolation::None, 0, "none"),
        (CodecViolation::Result, 1, "result"),
        (CodecViolation::Size, 2, "size"),
        (CodecViolation::Type, 3, "type"),
        (CodecViolation::Utf8, 4, "utf8"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(CodecViolation::from_raw(raw), member);
    }
    let beyond = CodecViolation::from_raw(5);
    assert_eq!((beyond.as_raw(), beyond.name()), (5, "unknown"));
}

#[test]
fn severity_matches_native_vocabulary() {
    for (member, raw, name) in [
        (Severity::Error, 0, "error"),
        (Severity::Warning, 1, "warning"),
        (Severity::Info, 2, "info"),
    ] {
        assert_eq!(member.name(), name);
        assert_eq!(member.as_raw(), raw);
        assert_eq!(Severity::from_raw(raw), member);
    }
    let beyond = Severity::from_raw(3);
    assert_eq!((beyond.as_raw(), beyond.name()), (3, "unknown"));
}
