#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Marek Cingel
"""Generate binding diagnostic vocabularies from the public C enums.

Values come from the C headers and expected spellings from the C name tables.
Rust, Go and Python receive typed categories plus tests that compare every
member with the linked C name function. Run with --check in CI to reject
stale generated files.
"""
import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]

# (binding type, C typedef without _t, enumerator prefix, header, C name function, Python key)
FAMILIES = (
    ("ReaderOperation", "tlv_reader_operation", "TLV_READER_OP_",
     "tlv/include/tlv/reader/diagnostic.h", "tlv_reader_operation_string", "reader_operation"),
    ("WriterOperation", "tlv_writer_operation", "TLV_WRITER_OP_",
     "tlv/include/tlv/writer/writer.h", "tlv_writer_operation_string", "writer_operation"),
    ("QueryErrorKind", "tlv_query_error_kind", "TLV_QUERY_ERROR_",
     "tlv/include/tlv/query/program.h", "tlv_query_error_kind_string", "query_error_kind"),
    ("QueryCause", "tlv_query_cause", "TLV_QUERY_CAUSE_",
     "tlv/include/tlv/query/program.h", "tlv_query_cause_string", "query_cause"),
    ("SchemaIssue", "tlv_schema_issue_kind", "TLV_SCHEMA_ISSUE_",
     "tlv/include/tlv/schema/schema.h", "tlv_schema_issue_kind_string", "schema_issue_kind"),
    ("SchemaDefinitionKind", "tlv_schema_definition_kind", "TLV_SCHEMA_DEFINITION_",
     "tlv/include/tlv/schema/schema.h", "tlv_schema_definition_kind_string",
     "schema_definition_kind"),
    ("CodecOperation", "tlv_codec_operation", "TLV_CODEC_OP_",
     "tlv/include/tlv/codec/diagnostic.h", "tlv_codec_operation_string", "codec_operation"),
    ("CodecCause", "tlv_codec_cause", "TLV_CODEC_CAUSE_",
     "tlv/include/tlv/codec/diagnostic.h", "tlv_codec_cause_string", "codec_cause"),
    ("CodecViolation", "tlv_codec_violation", "TLV_CODEC_VIOLATION_",
     "tlv/include/tlv/codec/diagnostic.h", "tlv_codec_violation_string", "codec_violation"),
    ("Severity", "tlv_diagnostic_severity", "TLV_DIAGNOSTIC_SEVERITY_",
     "tlv/include/tlv/diagnostic.h", "tlv_diagnostic_severity_string", "diagnostic_severity"),
)
NAME_TABLES = ("tlv/src/diagnostic_strings.c", "tlv/src/diagnostic.c")

HEADER = "// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Marek Cingel\n"
PY_HEADER = "# SPDX-License-Identifier: MIT\n# Copyright (c) 2026 Marek Cingel\n"
NOTICE = "Generated by scripts/generate_diagnostic_vocabulary.py; do not edit."
COMMENT = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)
CASE = re.compile(r'case\s+(TLV_\w+)\s*:\s*return\s+"(\w+)"\s*;')


def parse_enum(typedef, header):
    source = COMMENT.sub("", (ROOT / header).read_text(encoding="utf-8"))
    match = re.search(r"typedef\s+enum\s+%s\s*\{(.*?)\}\s*%s_t\s*;" % (typedef, typedef),
                      source, re.S)
    if not match:
        raise SystemExit(f"{header}: enum {typedef} not found")
    members, value = [], -1
    for entry in filter(None, (part.strip() for part in match[1].split(","))):
        name, _, explicit = (text.strip() for text in entry.partition("="))
        value = int(explicit, 0) if explicit else value + 1
        members.append((name, value))
    return members


def load():
    names = {}
    for table in NAME_TABLES:
        names.update(CASE.findall((ROOT / table).read_text(encoding="utf-8")))
    families = []
    for binding, typedef, prefix, header, function, key in FAMILIES:
        members = []
        for enumerator, value in parse_enum(typedef, header):
            if not enumerator.startswith(prefix) or enumerator not in names:
                raise SystemExit(f"{enumerator}: missing prefix {prefix} or C name")
            members.append((enumerator[len(prefix):], value, names[enumerator]))
        families.append((binding, typedef, function, key, members))
    return families


def camel(suffix):
    return "".join(part.capitalize() for part in suffix.split("_"))


def rust(families):
    out = [HEADER, "\n", f"//! Typed diagnostic vocabulary with canonical C names. {NOTICE}\n",
           "use opentlv_sys as native;\nuse std::{ffi::CStr, fmt};\n\n",
           "/// Unrecognized native category value, retained without loss.\n",
           "///\n/// Only produced by `from_raw()` for values outside the known vocabulary, so\n",
           "/// equality and hashing agree with the raw value.\n",
           "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n",
           "pub struct RawCategory(i32);\n\n",
           "impl RawCategory {\n    /// Original C category value.\n",
           "    pub fn as_raw(self) -> i32 {\n        self.0\n    }\n}\n"]
    for binding, _, function, _, members in families:
        out.append(f"\n/// Canonical {binding} diagnostic category.\n")
        out.append("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n#[non_exhaustive]\n")
        out.append(f"pub enum {binding} {{\n")
        for suffix, _, name in members:
            out.append(f"    /// C `{name}` category.\n    {camel(suffix)},\n")
        out.append("    /// Unrecognized native value, retained without loss.\n")
        out.append("    Unrecognized(RawCategory),\n}\n")
        out.append(f"impl {binding} {{\n")
        out.append("    /// Preserve a native category, including future values.\n")
        out.append("    pub fn from_raw(value: i32) -> Self {\n        match value {\n")
        for suffix, value, _ in members:
            out.append(f"            {value} => Self::{camel(suffix)},\n")
        out.append("            other => Self::Unrecognized(RawCategory(other)),\n        }\n    }\n")
        out.append("    /// Original C category value.\n")
        out.append("    pub fn as_raw(self) -> i32 {\n        match self {\n")
        for suffix, value, _ in members:
            out.append(f"            Self::{camel(suffix)} => {value},\n")
        out.append("            Self::Unrecognized(value) => value.as_raw(),\n        }\n    }\n")
        out.append("    /// Program-lifetime canonical C spelling.\n")
        out.append("    pub fn name(self) -> &'static str {\n")
        out.append("        // SAFETY: every integer maps to a static NUL-terminated ASCII string.\n")
        out.append(f"        unsafe {{ CStr::from_ptr(native::{function}(self.as_raw())) }}\n")
        out.append("            .to_str()\n            .expect(\"ASCII diagnostic label\")\n")
        out.append("    }\n}\n")
        out.append(f"impl Default for {binding} {{\n    fn default() -> Self {{\n")
        out.append("        Self::from_raw(0)\n    }\n}\n")
        out.append(f"impl fmt::Display for {binding} {{\n")
        out.append("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n")
        out.append("        f.write_str(self.name())\n    }\n}\n")
    return "".join(out)


def rust_test(families):
    out = [HEADER, f"//! {NOTICE}\n", "use opentlv::{\n"]
    imports = sorted(binding for binding, *_ in families)
    # Fill import lines as rustfmt does: indented, comma-terminated, at most 100 columns.
    line = "   "
    for name in imports:
        if len(line) + len(name) + 2 > 100:
            out.append(line + "\n")
            line = "   "
        line += f" {name},"
    out.append(line + "\n};\n")
    for binding, _, _, _, members in families:
        snake = re.sub(r"(?<!^)([A-Z])", r"_\1", binding).lower()
        out.append(f"\n#[test]\nfn {snake}_matches_native_vocabulary() {{\n    for (member, raw, name) in [\n")
        for suffix, value, name in members:
            out.append(f"        ({binding}::{camel(suffix)}, {value}, \"{name}\"),\n")
        out.append("    ] {\n        assert_eq!(member.name(), name);\n")
        out.append("        assert_eq!(member.as_raw(), raw);\n")
        out.append(f"        assert_eq!({binding}::from_raw(raw), member);\n    }}\n")
        beyond = max(value for _, value, _ in members) + 1
        out.append(f"    let beyond = {binding}::from_raw({beyond});\n")
        out.append(f"    assert_eq!((beyond.as_raw(), beyond.name()), ({beyond}, \"unknown\"));\n}}\n")
    return "".join(out)


def go(families):
    out = [HEADER, "\n", f"// {NOTICE}\n\n", "package opentlv\n\n",
           'import "github.com/marekcingel/OpenTLV/bindings/go/internal/capi"\n']
    for binding, _, _, _, members in families:
        out.append(f"\n// {binding} identifies a canonical C diagnostic category.\n")
        out.append(f"type {binding} int\n\nconst (\n")
        width = max(len(binding + camel(suffix)) for suffix, _, _ in members)
        for suffix, value, _ in members:
            out.append(f"\t{(binding + camel(suffix)).ljust(width)} {binding} = {value}\n")
        out.append(")\n\n// String returns the canonical C spelling, or \"unknown\".\n")
        out.append(f"func (v {binding}) String() string {{ return capi.{binding}Name(int(v)) }}\n")
    return "".join(out)


def go_test(families):
    out = [HEADER, f"// {NOTICE}\n\n", "package tests\n\n", "import (\n\t\"fmt\"\n\t\"testing\"\n\n",
           '\ttlv "github.com/marekcingel/OpenTLV/bindings/go"\n)\n\n',
           "func TestDiagnosticVocabularyMatchesNative(t *testing.T) {\n",
           "\tcases := []struct {\n\t\tvalue fmt.Stringer\n\t\tname  string\n\t}{\n"]
    for binding, _, _, _, members in families:
        for suffix, _, name in members:
            out.append(f"\t\t{{tlv.{binding}{camel(suffix)}, \"{name}\"}},\n")
        beyond = max(value for _, value, _ in members) + 1
        out.append(f"\t\t{{tlv.{binding}({beyond}), \"unknown\"}},\n")
    out.append("\t}\n\tfor _, c := range cases {\n")
    out.append("\t\tif got := c.value.String(); got != c.name {\n")
    out.append("\t\t\tt.Errorf(\"%T(%v): got %q, want %q\", c.value, c.value, got, c.name)\n")
    out.append("\t\t}\n\t}\n}\n")
    return "".join(out)


PYTHON_CATEGORY = '''class _Category(IntEnum):
    @classmethod
    def _missing_(cls, value):
        if not isinstance(value, int):
            return None
        # Cache the pseudo-member so equal unknown values stay identical.
        item = int.__new__(cls, value)
        item._name_ = f"UNKNOWN_{value}"
        item._value_ = value
        return cls._value2member_map_.setdefault(value, item)

    @property
    def label(self):
        """Canonical C spelling; "unknown" for unrecognized values."""
        if not _INT_MIN <= self.value <= _INT_MAX:
            return "unknown"
        return _native.diagnostic_name(_FAMILIES[type(self).__name__], self.value)
'''


def python(families):
    out = [PY_HEADER, "\n",
           '"""Typed C diagnostic categories; unknown values keep their numeric identity.\n\n',
           f'{NOTICE}\n"""\n', "from enum import IntEnum\n", "import _opentlv as _native\n\n",
           "_INT_MIN, _INT_MAX = -(2 ** 31), 2 ** 31 - 1\n", "_FAMILIES = {\n"]
    out.extend(f'    "{binding}": "{key}",\n' for binding, _, _, key, _ in families)
    out.append("}\n\n\n" + PYTHON_CATEGORY)
    for binding, _, _, _, members in families:
        out.append(f"\n\nclass {binding}(_Category):\n")
        out.append(f'    """Canonical {binding} category."""\n')
        for suffix, value, _ in members:
            out.append(f"    {suffix} = {value}\n")
    return "".join(out)


def python_test(families):
    out = [PY_HEADER, f'"""{NOTICE}"""\n', "import pytest\n", "from opentlv import (\n"]
    out.extend(f"    {binding},\n" for binding, *_ in families)
    out.append(")\n\n\nVOCABULARY = [\n")
    for binding, _, _, _, members in families:
        for suffix, value, name in members:
            out.append(f'    ({binding}, "{suffix}", {value}, "{name}"),\n')
    out.append("]\n\n\n")
    out.append('@pytest.mark.parametrize("category,member,value,label", VOCABULARY)\n')
    out.append("def test_member_matches_native_vocabulary(category, member, value, label):\n")
    out.append("    assert category[member].value == value\n")
    out.append("    assert category(value) is category[member]\n")
    out.append("    assert category[member].label == label\n\n\n")
    out.append("@pytest.mark.parametrize(\"category,beyond\", [\n")
    for binding, _, _, _, members in families:
        out.append(f"    ({binding}, {max(value for _, value, _ in members) + 1}),\n")
    out.append("])\n")
    out.append("def test_next_value_is_unknown(category, beyond):\n")
    out.append("    assert category(beyond).label == \"unknown\"\n")
    return "".join(out)


OUTPUTS = (
    ("bindings/rust/opentlv/src/diagnostic_kind.rs", rust),
    ("bindings/rust/opentlv/tests/diagnostic_vocabulary.rs", rust_test),
    ("bindings/go/diagnostic_kind.go", go),
    ("bindings/go/tests/diagnostic_vocabulary_test.go", go_test),
    ("bindings/python/opentlv/src/opentlv/diagnostic.py", python),
    ("bindings/python/opentlv/tests/test_diagnostic_vocabulary.py", python_test),
)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail when a generated file differs instead of writing it")
    args = parser.parse_args()
    families = load()
    stale = []
    for path, render in OUTPUTS:
        target = ROOT / path
        text = render(families)
        current = target.read_text(encoding="utf-8").replace("\r\n", "\n") if target.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path)
        else:
            target.write_bytes(text.encode("utf-8"))
            print(f"updated {path}")
    if stale:
        print("stale generated diagnostic vocabulary; run "
              "scripts/generate_diagnostic_vocabulary.py:\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
