cmake_minimum_required(VERSION 3.16)

function(check expected pattern)
    execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: expected ${expected}, got ${result}\n${output}\n${error}")
    endif()
    if(expected EQUAL 0)
        if(NOT error STREQUAL "")
            message(FATAL_ERROR "Unexpected stderr: ${error}")
        endif()
        set(actual "${output}")
    else()
        set(actual "${error}")
    endif()
    if(NOT actual MATCHES "${pattern}")
        message(FATAL_ERROR "${ARGN}: expected /${pattern}/, got '${actual}'")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()

check(0 "Usage:" --help)
check(0 "otlv " --version)
check(2 "missing command")
check(2 "unknown command" unknown)
check(0 "" formats)
set(expected_formats "")
foreach(pair IN ITEMS "DEFAULT|default" "FIXED|fixed-1byte" "BER|ber" "DER|der")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 flag)
    list(GET parts 1 name)
    if(HAS_${flag})
        string(APPEND expected_formats "${name}\n")
    else()
        check(2 "disabled format" validate --format "${name}" --hex " ")
    endif()
endforeach()
check(0 "" formats)
if(NOT last_output STREQUAL expected_formats)
    message(FATAL_ERROR "Incorrect format list: '${last_output}'")
endif()
check(2 "disabled format" validate --format unknown --hex " ")
check(2 "exactly one" dump --format ber)
check(2 "exactly one" dump --format ber --hex AA --input -)
check(2 "duplicate" dump --format ber --format ber --hex AA)
check(2 "missing option value" dump --hex)
check(2 "nonnegative" dump --format ber --hex AA --max-elements -1)
check(2 "nonnegative" dump --format ber --hex AA --max-input-size 999999999999999999999999)
check(2 "0..64" dump --format ber --hex AA --max-depth 65)
check(2 "requires dump" validate --format ber --hex AA --tree)
check(2 "conflicting color" dump --format ber --hex AA --force-color --no-color)
check(2 "requires --input" dump --format ber --hex AA --input-encoding hex)
check(2 "binary or hex" dump --format ber --input - --input-encoding unknown)
check(2 "requires --profile" dump --format ber --hex AA --describe)
check(2 "requires --format ber" validate --format der --hex AA --profile emv)
check(2 "requires --format ber" dump --format der --hex AA --profile emv)
check(2 "unknown profile" dump --format ber --hex AA --profile unknown)
check(2 "--decode requires --profile" dump --format ber --hex AA --decode)
check(2 "require dump" validate --format ber --hex AA --output json)
check(2 "require dump" validate --format ber --hex AA --decode --profile emv)
check(2 "text or json" dump --format ber --hex AA --output xml)

foreach(pair IN ITEMS "DEFAULT|default" "FIXED|fixed-1byte" "BER|ber" "DER|der")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 flag)
    list(GET parts 1 name)
    if(NOT HAS_${flag})
        continue()
    endif()
    check(0 "^$" validate --format "${name}" --hex " ")
    execute_process(COMMAND "${CLI}" validate --format "${name}" --hex ""
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "" OR NOT error STREQUAL "")
        message(FATAL_ERROR "Empty hex input failed: ${result} ${output} ${error}")
    endif()
    check(0 "^$" validate --format "${name}" --hex " " --max-input-size 0 --max-elements 0)
    check(0 "offset=0 tag=04 length=1 value=AA" dump --format "${name}" --hex "04 01 aA")
    check(0 "^{\"elements\":\\[{\"length\":1,\"offset\":0,\"tag\":\"04\",\"value\":\"AA\"}\\]}\n$" dump --format "${name}" --hex "0401AA" --output json)
    string(ASCII 27 escape)
    if(last_output MATCHES "${escape}")
        message(FATAL_ERROR "Redirected output must be colorless by default")
    endif()
    check(0 "${escape}" dump --format "${name}" --hex "0401AA" --force-color)
    check(0 "tag=04" dump --format "${name}" --hex "0401AA" --no-color)
    if(last_output MATCHES "${escape}")
        message(FATAL_ERROR "--no-color emitted ANSI escapes")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" "04 01\naa\n")
    check(0 "value=AA" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" --input-encoding hex --max-input-size 3)
    check(3 "input-size limit" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" --input-encoding hex --max-input-size 2)
    execute_process(COMMAND "${CLI}" dump --format "${name}" --input - --input-encoding hex
        INPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "value=AA" OR NOT error STREQUAL "")
        message(FATAL_ERROR "Hex stdin failed: ${result} ${output} ${error}")
    endif()
    foreach(hex IN ITEMS "0" "0G" "G0" "0 4" "0x04")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" "${hex}")
        check(2 "byte pairs" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" --input-encoding hex)
    endforeach()
    check(0 "offset=3 tag=04 length=0 value=" dump --format "${name}" --hex "0401AA0400")
    check(0 "^$" validate --format "${name}" --hex "0401AA" --max-input-size 3 --max-elements 1)
    if(name STREQUAL "der")
        set(truncated_offset 2)
        set(trailing_offset 4)
    else()
        set(truncated_offset 0)
        set(trailing_offset 3)
    endif()
    check(1 "TLV_ERR_.*byte ${truncated_offset}" validate --format "${name}" --hex "0402AA")
    check(1 "TLV_ERR_.*byte ${trailing_offset}" dump --format "${name}" --hex "0401AA04")
    if(NOT last_output MATCHES "offset=0")
        message(FATAL_ERROR "Expected partial dump before trailing error")
    endif()
    check(3 "input-size limit" validate --format "${name}" --hex "0401AA" --max-input-size 2)
    check(3 "TLV_ERR_LIMIT" validate --format "${name}" --hex "04000400" --max-elements 1)
    foreach(hex IN ITEMS "0" "0G" "G0" "0 4" "0x04")
        check(2 "byte pairs" dump --format "${name}" --hex "${hex}")
    endforeach()
    check(3 "cannot open" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/nonexistent-cli-input")
    # Binary fixture includes LF, CR, Ctrl-Z, and a high byte to exercise Windows stdin.
    configure_file("${CMAKE_CURRENT_LIST_DIR}/input.bin"
        "${CMAKE_CURRENT_BINARY_DIR}/cli-input.bin" COPYONLY)
    check(0 "value=0A0D1AFF" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-input.bin")
    if(UNIX AND EXISTS "/dev/full")
        execute_process(COMMAND "${CLI}" dump --format "${name}" --hex "0401AA"
            OUTPUT_FILE /dev/full RESULT_VARIABLE result ERROR_VARIABLE error)
        if(NOT result EQUAL 3 OR NOT error MATCHES "cannot write output")
            message(FATAL_ERROR "Output error not reported: ${result} ${error}")
        endif()
    endif()
    execute_process(COMMAND "${CLI}" dump --format "${name}" --input -
        INPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/cli-input.bin"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT error STREQUAL "" OR NOT output MATCHES "value=0A0D1AFF")
        message(FATAL_ERROR "Binary stdin failed: ${result} ${output} ${error}")
    endif()
    if(name STREQUAL "default" OR name STREQUAL "fixed-1byte")
        check(2 "only BER and DER" dump --format "${name}" --hex " " --tree)
    else()
        check(0 "  offset=2 tag=04 length=1 value=AA" dump --format "${name}" --hex "30030401AA" --tree)
        check(0 "offset=0" dump --format "${name}" --hex "30030401AA")
        if(last_output MATCHES "offset=2")
            message(FATAL_ERROR "Default dump must show top-level elements only")
        endif()
        check(0 "^{\"elements\":\\[{\"elements\":\\[{\"length\":1,\"offset\":2,\"tag\":\"04\",\"value\":\"AA\"}\\],\"length\":3,\"offset\":0,\"tag\":\"30\",\"value\":\"0401AA\"}\\]}\n$"
            dump --format "${name}" --hex "30030401AA" --tree --output json)
        check(0 "^{\"elements\":\\[{\"length\":3,\"offset\":0,\"tag\":\"30\",\"value\":\"0401AA\"}\\]}\n$" dump --format "${name}" --hex "30030401AA" --output json)
        check(1 "TLV_ERR_" validate --format "${name}" --hex "30030402AA")
        check(3 "TLV_ERR_LIMIT" validate --format "${name}" --hex "30030401AA" --max-depth 0)
        check(3 "TLV_ERR_LIMIT" validate --format "${name}" --hex "30030401AA" --max-elements 1)
    endif()
endforeach()
if(HAS_BER)
    check(0 "offset=3 tag=9F1A requested-length=2" dump --format ber --pdol --hex "9F02069F1A02")
    check(0 "requested-length=128" dump --format ber --pdol --hex "9F0280")
    check(0 "requested-length=255" dump --format ber --pdol --hex "9F02FF")
    check(0 "requested-length=0" dump --format ber --pdol --hex "9F0200")
    check(0 "^$" validate --format ber --pdol --hex "9F02069F0206")
    check(0 "^$" validate --format ber --pdol --hex " ")
    check(1 "TLV_ERR_.*byte 0" validate --format ber --pdol --hex "9F")
    check(1 "TLV_ERR_BUFFER_TOO_SHORT.*byte 2" validate --format ber --pdol --hex "9F02")
    check(1 "TLV_ERR_INVALID_TAG_SIZE" validate --format ber --pdol --hex "DF810101")
    check(1 "TLV_ERR_INVALID_TAG" validate --format ber --pdol --hex "0000")
    check(3 "TLV_ERR_LIMIT.*byte 3" validate --format ber --pdol --hex "9F02069F1A02" --max-elements 1)
    check(2 "cannot use" dump --format ber --pdol --hex " " --pretty)
    check(2 "cannot use" dump --format ber --pdol --hex " " --profile emv --decode)
    check(2 "requires --format ber" dump --format der --pdol --hex " ")
    check(0 "^{\"elements\":\\[{\"offset\":0,\"requested_length\":6,\"tag\":\"9F02\"}\\]}\n$" dump --format ber --pdol --output json --hex "9F0206")
    if(HAS_EMV)
        check(0 "Amount Authorised" dump --format ber --pdol --hex "9F0206" --profile emv --describe)
        check(0 "\"name\":\"Amount Authorised\"" dump --format ber --pdol --output json --profile emv --hex "9F0206")
    endif()
    check(0 "" dump --format ber --hex "300730030401AA040030020400" --pretty --no-color)
    set(expected "offset=0 tag=30 length=7 value=30030401AA0400\n├── offset=2 tag=30 length=3 value=0401AA\n│   └── offset=4 tag=04 length=1 value=AA\n└── offset=7 tag=04 length=0 value=\noffset=9 tag=30 length=2 value=0400\n└── offset=11 tag=04 length=0 value=\n")
    if(NOT last_output STREQUAL expected)
        message(FATAL_ERROR "Incorrect graphical tree: ${last_output}")
    endif()
    check(0 "└── offset=2" dump --format ber --hex "30800401AA0000" --pretty)
    check(0 "length=3 encoding=indefinite" dump --format ber --hex "30800401AA0000" --tree)
    if(last_output MATCHES "tag=00")
        message(FATAL_ERROR "EOC displayed as an element")
    endif()
    check(0 "offset=7 tag=04" dump --format ber --hex "30800401AA00000400" --tree)
    check(1 "TLV_ERR_" validate --format ber --hex "30800401AA")
    check(1 "TLV_ERR_" validate --format ber --hex "04800000")
    check(0 "tag=9F1C" dump --format ber --hex "9F1C0112")
endif()
if(HAS_EMV)
    check(0 "Primary Account Number" dump --format ber --hex "5A0112" --profile emv)
    check(0 "Decimal digits; dictionary length: 1..10 bytes; step: 1" dump --format ber --hex "5A0112" --profile emv --describe)
    check(0 "Dedicated File" dump --format ber --hex "6F0784050102030405" --profile emv --pretty)
    check(0 "Unknown EMV tag" dump --format ber --hex "DF010100" --profile emv --describe)
    check(0 "Biometric Subtype" dump --format ber --hex "7F6005A103820101" --profile emv --pretty)
    check(0 "Unknown EMV tag" dump --format ber --hex "E103820101" --profile emv --pretty)
    # --decode: a known tag with a successful decode (Amount, Authorised: BCD n12 -> a decimal integer).
    check(0 "decoded=\"1000\"" dump --format ber --hex "9F0206000000001000" --profile emv --decode)
    # --decode: a tag outside the dictionary is skipped gracefully, without a decoded/decode-error field.
    check(0 "^offset=0 tag=DF01 length=1 value=00 name=\"Unknown EMV tag in this context\"\n$" dump --format ber --hex "DF010100" --profile emv --decode)
    # --decode: a value with the right length but an invalid BCD nibble reports a codec diagnostic.
    check(0 "decode-error=\"Invalid codec value\"" dump --format ber --hex "9F0206FFFFFFFFFFFF" --profile emv --decode)
    # --decode: a value kind with no codec (PAN is DIGITS, not BYTES/TEXT/TEMPLATE, so use a template tag instead).
    check(0 "^offset=0 tag=6F length=0 value= name=\"File Control Information \\(FCI\\) Template\"\n$" dump --format ber --hex "6F00" --profile emv --decode)
    check(0 "\"decoded\":\"12345678\"" dump --format ber --hex "5A0412345678" --profile emv --decode --output json)
    # Schema validation (#167): mandatory tags, forbidden/unknown tags, duplicate
    # tags, length constraints and nesting, with a tag/offset diagnostic
    # distinguishable from an ordinary format error.
    check(0 "^$" validate --format ber --profile emv --hex "6F098407A0000000031010") # DF Name only.
    # Missing mandatory DF Name: the distinct TLV_ERR_SCHEMA_MISSING (not
    # TLV_ERR_SCHEMA) never prints a tag, since its offset is only the end of
    # the FCI Template's (empty) value, not an element.
    check(1 "^otlv: schema TLV_ERR_SCHEMA_MISSING at byte 2: required schema field missing\n$"
        validate --format ber --profile emv --hex "6F00")
    check(1 "schema TLV_ERR_SCHEMA at byte 11 tag=50:" # Application Label forbidden directly under the FCI Template.
        validate --format ber --profile emv --hex "6F0C8407A0000000031010500141")
    check(1 "schema TLV_ERR_SCHEMA at byte 11 tag=84:" validate --format ber --profile emv # Duplicate DF Name.
        --hex "6F128407A00000000310108407A0000000031010")
    check(1 "schema TLV_ERR_INVALID_LENGTH at byte 2 tag=84:" # DF Name shorter than the dictionary minimum.
        validate --format ber --profile emv --hex "6F048402AABB")
    check(0 "^$" validate --format ber --profile emv # A nested, known-optional FCI Proprietary Template child.
        --hex "6F0C84053132333435A503500141")
    check(0 "^$" validate --format ber --profile emv --hex "770A82021980940408010100") # GPO response format 2: AIP + AFL.
    check(1 "^otlv: schema TLV_ERR_SCHEMA_MISSING at byte 6: required schema field missing\n$"
        validate --format ber --profile emv --hex "770482021980") # Missing mandatory AFL.
    check(0 "^$" validate --format ber --profile emv --hex "7003DF0100") # Unmodeled top-level template: accepted unchecked.
    check(1 "^otlv: TLV_ERR_BUFFER_TOO_SHORT" # A plain format error is not labeled "schema".
        validate --format ber --profile emv --hex "6F0AFF")
    # A missing-required-field offset is the end of its parent's (here,
    # empty) value, which coincides with the unrelated sibling GPO response
    # (770A...) that follows; TLV_ERR_SCHEMA_MISSING's dedicated diagnostic
    # (no "tag=") avoids misattributing the failure to that sibling.
    check(1 "^otlv: schema TLV_ERR_SCHEMA_MISSING at byte 2: required schema field missing\n$"
        validate --format ber --profile emv --hex "6F00770A82021980940408010100")
    check(0 "tag=6F" dump --format ber --profile emv --hex "6F00") # dump's --profile never runs schema checks.
else()
    check(2 "EMV profile is disabled" dump --format ber --hex " " --profile emv)
    check(2 "EMV profile is disabled" validate --format ber --hex " " --profile emv)
endif()
if(HAS_DER)
    check(1 "TLV_ERR_" validate --format der --hex "30800401AA0000")
    check(1 "TLV_ERR_" validate --format der --hex "048101AA")
endif()

# encode (#168): option errors, writer diagnostics, and encode -> dump round trips.
check(2 "encode requires --format and --tag" encode --format ber)
check(2 "encode requires --format and --tag" encode --tag 5A)
check(2 "not valid for encode" encode --format ber --tag 5A --hex AA)
check(2 "requires encode" dump --format ber --hex AA --tag 5A)
check(2 "output encoding must be binary or hex" encode --format ber --tag 5A --output-encoding text)
check(2 "complete hexadecimal byte pairs" encode --format ber --tag 5 --value 00)
check(2 "complete hexadecimal byte pairs" encode --format ber --tag 5A --value 0G)
check(2 "tag must not be empty" encode --format ber --tag " ")
check(2 "tag is longer" encode --format ber --tag 0102030405060708090A --value 00)
check(2 "disabled format" encode --format unknown --tag 5A)
check(2 "duplicate" encode --format ber --tag 5A --tag 5B)
if(HAS_BER)
    check(0 "^9F0206000000001000\n$" encode --format ber --tag 9F02 --value 000000001000)
    check(0 "^9F0206000000001000\n$" encode --format ber --tag "9f 02" --value "00 00 00 00 10 00")
    check(0 "^5A00\n$" encode --format ber --tag 5A)
    check(0 "^E1035A0112\n$" encode --format ber --tag E1 --value 5A0112)
    check(1 "cannot encode element 0: " encode --format ber --tag 00 --value AA)
    set(long_value "")
    foreach(i RANGE 1 200)
        string(APPEND long_value "AB")
    endforeach()
    check(0 "^5A81C8${long_value}
$" encode --format ber --tag 5A --value "${long_value}")
endif()

# Encode -> dump round trips, through hex text and through binary files.
function(round_trip format tag value)
    execute_process(COMMAND "${CLI}" encode --format "${format}" --tag "${tag}" --value "${value}"
        RESULT_VARIABLE result OUTPUT_VARIABLE hex ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "encode ${format} ${tag}: ${result} ${error}")
    endif()
    string(STRIP "${hex}" hex)
    check(0 "offset=0 tag=${tag} length=" dump --format "${format}" --hex "${hex}")
    check(0 "value=${value}" dump --format "${format}" --hex "${hex}")
    set(bin "${CMAKE_CURRENT_BINARY_DIR}/encode-roundtrip.bin")
    execute_process(COMMAND "${CLI}" encode --format "${format}" --tag "${tag}" --value "${value}"
        --output-encoding binary OUTPUT_FILE "${bin}" RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "binary encode ${format} ${tag}: ${result} ${error}")
    endif()
    file(READ "${bin}" binary_hex HEX)
    string(TOUPPER "${binary_hex}" binary_hex)
    if(NOT binary_hex STREQUAL hex)
        message(FATAL_ERROR "binary output ${binary_hex} differs from hex output ${hex}")
    endif()
    check(0 "value=${value}" dump --format "${format}" --input "${bin}")
    file(REMOVE "${bin}")
endfunction()

if(HAS_BER)
    round_trip(ber 9F02 000000001000)
    round_trip(ber 5A 00)
    round_trip(ber 5A "${long_value}")
endif()
if(HAS_DER)
    round_trip(der 04 AABBCC)
    check(1 "cannot encode element 0: " encode --format der --tag 00 --value AA)
endif()
if(HAS_FIXED)
    round_trip(fixed-1byte 01 AABB)
    check(1 "cannot encode element 0: " encode --format fixed-1byte --tag 0102 --value AA)
endif()

# tag (#169): EMV dictionary lookup from the profile layer.
check(2 "tag requires a hex tag" tag)
check(2 "tag requires a hex tag" tag --profile emv)
check(2 "tag requires --profile" tag 9F02)
check(2 "unknown profile" tag 9F02 --profile unknown)
check(2 "not valid for tag" tag 9F02 --profile emv --format ber)
check(2 "not valid for tag" tag 9F02 --profile emv --hex AA)
check(2 "duplicate" tag 9F02 --profile emv --profile emv)
check(2 "output must be text or json" tag 9F02 --profile emv --output xml)
if(HAS_EMV)
    check(0 "^Tag:         9F02\nName:        Amount Authorised\nType:        Numeric value[^\n]*\nForm:        Primitive\nLength:      6\n$" tag 9F02 --profile emv)
    check(0 "^Tag:         9F02\n" tag "9f 02" --profile emv)
    check(0 "Name:        Primary Account Number" tag 5A --profile emv)
    check(0 "Length:      1..10\n" tag 5A --profile emv)
    check(0 "Form:        Constructed" tag 6F --profile emv)
    check(0 "Length step: 4\n" tag 94 --profile emv)
    # Unknown tags are a result, not malformed TLV data.
    check(0 "^Tag:         DF01\nResult:      Unknown tag" tag DF01 --profile emv)
    check(0 "^{\"known\":false,\"profile\":\"emv\",\"tag\":\"DF01\"}\n$" tag DF01 --profile emv --output json)
    check(0 "\"constructed\":false" tag 9F02 --profile emv --output json)
    check(0 "\"known\":true" tag 9F02 --profile emv --output json)
    check(0 "\"max_length\":6" tag 9F02 --profile emv --output json)
    check(0 "\"min_length\":6" tag 9F02 --profile emv --output json)
    check(0 "\"name\":\"Amount Authorised\"" tag 9F02 --profile emv --output json)
    check(0 "\"tag\":\"9F02\"" tag 9F02 --profile emv --output json)
    check(0 "\"constructed\":true" tag 6F --profile emv --output json)
    check(0 "\"length_step\":4" tag 94 --profile emv --output json)
    # Invalid tags are rejected.
    check(2 "complete hexadecimal byte pairs" tag 9F0 --profile emv)
    check(2 "complete hexadecimal byte pairs" tag ZZ --profile emv)
    check(2 "tag must not be empty" tag " " --profile emv)
    check(2 "not a single complete BER tag" tag 9F --profile emv)
    check(2 "not a single complete BER tag" tag 5A01 --profile emv)
    check(2 "tag is longer" tag 0102030405060708090A --profile emv)
else()
    check(2 "EMV profile is disabled" tag 9F02 --profile emv)
endif()

# tags (#169): dictionary listing.
check(2 "tags requires --profile" tags)
check(2 "unknown profile" tags --profile unknown)
check(2 "not valid for tags" tags --profile emv --format ber)
check(2 "not valid for tags" tags --profile emv --hex AA)
check(2 "option requires tags" dump --format ber --hex AA --search x)
check(2 "not valid for tag" tag 9F02 --profile emv --search x)
check(2 "not valid for encode" encode --format ber --tag 5A --search x)
check(2 "missing option value" tags --profile emv --search)
check(2 "duplicate" tags --profile emv --search a --search b)
check(2 "output must be text or json" tags --profile emv --output xml)
if(HAS_EMV)
    check(0 "(^|\n)5A      Primary Account Number" tags --profile emv)
    check(0 "(^|\n)9F02    Amount Authorised\n" tags --profile emv)
    check(0 "^42 " tags --profile emv)
    check(0 "^81      Amount Authorised Binary\n9F02    Amount Authorised\n9F03    Amount Other\n" tags --profile emv --search "AMOUNT")
    check(0 "^94      Application File Locator \\(AFL\\)\n$" tags --profile emv --search "file locator")
    check(0 "^$" tags --profile emv --search "no such tag name")
    check(0 "^{\"profile\":\"emv\",\"tags\":\\[\\]}\n$" tags --profile emv --search "no such tag name" --output json)
    check(0 "\"length_step\":4,\"max_length\":252,\"min_length\":4,\"name\":\"Application File Locator \\(AFL\\)\"" tags --profile emv --search afl --output json)
    check(0 "\"tag\":\"9F02\"" tags --profile emv --output json)
    check(0 "\"tag\":\"6F\"" tags --profile emv --output json)
endif()
