cmake_minimum_required(VERSION 3.16)

function(check expected pattern)
    execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error ENCODING UTF-8)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: expected ${expected}, got ${result}\n${output}\n${error}")
    endif()
    if(expected EQUAL 0)
        if(NOT error STREQUAL "")
            message(FATAL_ERROR "Unexpected stderr: ${error}")
        endif()
        set(actual "${output}")
    else()
        set(actual "${error}")
    endif()
    if(NOT actual MATCHES "${pattern}")
        message(FATAL_ERROR "${ARGN}: expected /${pattern}/, got '${actual}'")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()

check(0 "Usage:" --help)
check(0 "opentlv " --version)
check(2 "missing command")
check(2 "unknown command" unknown)
check(0 "" formats)
set(expected_formats "")
foreach(pair IN ITEMS "DEFAULT|default" "FIXED|fixed-1byte" "BER|ber" "DER|der")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 flag)
    list(GET parts 1 name)
    if(HAS_${flag})
        string(APPEND expected_formats "${name}\n")
    else()
        check(2 "disabled format" validate --format "${name}" --hex " ")
    endif()
endforeach()
check(0 "" formats)
if(NOT last_output STREQUAL expected_formats)
    message(FATAL_ERROR "Incorrect format list: '${last_output}'")
endif()
check(2 "disabled format" validate --format unknown --hex " ")
check(2 "exactly one" dump --format ber)
check(2 "exactly one" dump --format ber --hex AA --input -)
check(2 "duplicate" dump --format ber --format ber --hex AA)
check(2 "missing option value" dump --hex)
check(2 "nonnegative" dump --format ber --hex AA --max-elements -1)
check(2 "nonnegative" dump --format ber --hex AA --max-input-size 999999999999999999999999)
check(2 "0..64" dump --format ber --hex AA --max-depth 65)
check(2 "requires dump" validate --format ber --hex AA --tree)
check(2 "conflicting color" dump --format ber --hex AA --force-color --no-color)
check(2 "requires --input" dump --format ber --hex AA --input-encoding hex)
check(2 "binary or hex" dump --format ber --input - --input-encoding unknown)
check(2 "requires --profile" dump --format ber --hex AA --describe)
check(2 "require dump" validate --format ber --hex AA --profile emv)
check(2 "require --format ber" dump --format der --hex AA --profile emv)
check(2 "unknown profile" dump --format ber --hex AA --profile unknown)

foreach(pair IN ITEMS "DEFAULT|default" "FIXED|fixed-1byte" "BER|ber" "DER|der")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 flag)
    list(GET parts 1 name)
    if(NOT HAS_${flag})
        continue()
    endif()
    check(0 "^$" validate --format "${name}" --hex " ")
    execute_process(COMMAND "${CLI}" validate --format "${name}" --hex ""
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "" OR NOT error STREQUAL "")
        message(FATAL_ERROR "Empty hex input failed: ${result} ${output} ${error}")
    endif()
    check(0 "^$" validate --format "${name}" --hex " " --max-input-size 0 --max-elements 0)
    check(0 "offset=0 tag=04 length=1 value=AA" dump --format "${name}" --hex "04 01 aA")
    string(ASCII 27 escape)
    if(last_output MATCHES "${escape}")
        message(FATAL_ERROR "Redirected output must be colorless by default")
    endif()
    check(0 "${escape}" dump --format "${name}" --hex "0401AA" --force-color)
    check(0 "tag=04" dump --format "${name}" --hex "0401AA" --no-color)
    if(last_output MATCHES "${escape}")
        message(FATAL_ERROR "--no-color emitted ANSI escapes")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" "04 01\naa\n")
    check(0 "value=AA" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" --input-encoding hex --max-input-size 3)
    check(3 "input-size limit" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" --input-encoding hex --max-input-size 2)
    execute_process(COMMAND "${CLI}" dump --format "${name}" --input - --input-encoding hex
        INPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "value=AA" OR NOT error STREQUAL "")
        message(FATAL_ERROR "Hex stdin failed: ${result} ${output} ${error}")
    endif()
    foreach(hex IN ITEMS "0" "0G" "G0" "0 4" "0x04")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" "${hex}")
        check(2 "byte pairs" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-hex.txt" --input-encoding hex)
    endforeach()
    check(0 "offset=3 tag=04 length=0 value=" dump --format "${name}" --hex "0401AA0400")
    check(0 "^$" validate --format "${name}" --hex "0401AA" --max-input-size 3 --max-elements 1)
    if(name STREQUAL "der")
        set(truncated_offset 2)
        set(trailing_offset 4)
    else()
        set(truncated_offset 0)
        set(trailing_offset 3)
    endif()
    check(1 "TLV_ERR_.*byte ${truncated_offset}" validate --format "${name}" --hex "0402AA")
    check(1 "TLV_ERR_.*byte ${trailing_offset}" dump --format "${name}" --hex "0401AA04")
    if(NOT last_output MATCHES "offset=0")
        message(FATAL_ERROR "Expected partial dump before trailing error")
    endif()
    check(3 "input-size limit" validate --format "${name}" --hex "0401AA" --max-input-size 2)
    check(3 "TLV_ERR_LIMIT" validate --format "${name}" --hex "04000400" --max-elements 1)
    foreach(hex IN ITEMS "0" "0G" "G0" "0 4" "0x04")
        check(2 "byte pairs" dump --format "${name}" --hex "${hex}")
    endforeach()
    check(3 "cannot open" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/nonexistent-cli-input")
    # Binary fixture includes LF, CR, Ctrl-Z, and a high byte to exercise Windows stdin.
    configure_file("${CMAKE_CURRENT_LIST_DIR}/input.bin"
        "${CMAKE_CURRENT_BINARY_DIR}/cli-input.bin" COPYONLY)
    check(0 "value=0A0D1AFF" dump --format "${name}" --input "${CMAKE_CURRENT_BINARY_DIR}/cli-input.bin")
    if(UNIX AND EXISTS "/dev/full")
        execute_process(COMMAND "${CLI}" dump --format "${name}" --hex "0401AA"
            OUTPUT_FILE /dev/full RESULT_VARIABLE result ERROR_VARIABLE error)
        if(NOT result EQUAL 3 OR NOT error MATCHES "cannot write output")
            message(FATAL_ERROR "Output error not reported: ${result} ${error}")
        endif()
    endif()
    execute_process(COMMAND "${CLI}" dump --format "${name}" --input -
        INPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/cli-input.bin"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT error STREQUAL "" OR NOT output MATCHES "value=0A0D1AFF")
        message(FATAL_ERROR "Binary stdin failed: ${result} ${output} ${error}")
    endif()
    if(name STREQUAL "default" OR name STREQUAL "fixed-1byte")
        check(2 "only BER and DER" dump --format "${name}" --hex " " --tree)
    else()
        check(0 "  offset=2 tag=04 length=1 value=AA" dump --format "${name}" --hex "30030401AA" --tree)
        check(0 "offset=0" dump --format "${name}" --hex "30030401AA")
        if(last_output MATCHES "offset=2")
            message(FATAL_ERROR "Default dump must show top-level elements only")
        endif()
        check(1 "TLV_ERR_" validate --format "${name}" --hex "30030402AA")
        check(3 "TLV_ERR_LIMIT" validate --format "${name}" --hex "30030401AA" --max-depth 0)
        check(3 "TLV_ERR_LIMIT" validate --format "${name}" --hex "30030401AA" --max-elements 1)
    endif()
endforeach()
if(HAS_BER)
    check(0 "offset=3 tag=9F1A requested-length=2" dump --format ber --pdol --hex "9F02069F1A02")
    check(0 "requested-length=128" dump --format ber --pdol --hex "9F0280")
    check(0 "requested-length=255" dump --format ber --pdol --hex "9F02FF")
    check(0 "requested-length=0" dump --format ber --pdol --hex "9F0200")
    check(0 "^$" validate --format ber --pdol --hex "9F02069F0206")
    check(0 "^$" validate --format ber --pdol --hex " ")
    check(1 "TLV_ERR_.*byte 0" validate --format ber --pdol --hex "9F")
    check(1 "TLV_ERR_BUFFER_TOO_SHORT.*byte 2" validate --format ber --pdol --hex "9F02")
    check(1 "TLV_ERR_INVALID_TAG_SIZE" validate --format ber --pdol --hex "DF810101")
    check(1 "TLV_ERR_INVALID_TAG" validate --format ber --pdol --hex "0000")
    check(3 "TLV_ERR_LIMIT.*byte 3" validate --format ber --pdol --hex "9F02069F1A02" --max-elements 1)
    check(2 "cannot use" dump --format ber --pdol --hex " " --pretty)
    check(2 "requires --format ber" dump --format der --pdol --hex " ")
    if(HAS_EMV)
        check(0 "Amount Authorised" dump --format ber --pdol --hex "9F0206" --profile emv --describe)
    endif()
    check(0 "" dump --format ber --hex "300730030401AA040030020400" --pretty --no-color)
    set(expected "offset=0 tag=30 length=7 value=30030401AA0400\n├── offset=2 tag=30 length=3 value=0401AA\n│   └── offset=4 tag=04 length=1 value=AA\n└── offset=7 tag=04 length=0 value=\noffset=9 tag=30 length=2 value=0400\n└── offset=11 tag=04 length=0 value=\n")
    if(NOT last_output STREQUAL expected)
        message(FATAL_ERROR "Incorrect graphical tree: ${last_output}")
    endif()
    check(0 "└── offset=2" dump --format ber --hex "30800401AA0000" --pretty)
    check(0 "length=3 encoding=indefinite" dump --format ber --hex "30800401AA0000" --tree)
    if(last_output MATCHES "tag=00")
        message(FATAL_ERROR "EOC displayed as an element")
    endif()
    check(0 "offset=7 tag=04" dump --format ber --hex "30800401AA00000400" --tree)
    check(1 "TLV_ERR_" validate --format ber --hex "30800401AA")
    check(1 "TLV_ERR_" validate --format ber --hex "04800000")
    check(0 "tag=9F1C" dump --format ber --hex "9F1C0112")
endif()
if(HAS_EMV)
    check(0 "Primary Account Number" dump --format ber --hex "5A0112" --profile emv)
    check(0 "Decimal digits; dictionary length: 1..10 bytes; step: 1" dump --format ber --hex "5A0112" --profile emv --describe)
    check(0 "Dedicated File" dump --format ber --hex "6F0784050102030405" --profile emv --pretty)
    check(0 "Unknown EMV tag" dump --format ber --hex "DF010100" --profile emv --describe)
    check(0 "Biometric Subtype" dump --format ber --hex "7F6005A103820101" --profile emv --pretty)
    check(0 "Unknown EMV tag" dump --format ber --hex "E103820101" --profile emv --pretty)
else()
    check(2 "EMV profile is disabled" dump --format ber --hex " " --profile emv)
endif()
if(HAS_DER)
    check(1 "TLV_ERR_" validate --format der --hex "30800401AA0000")
    check(1 "TLV_ERR_" validate --format der --hex "048101AA")
endif()
