# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Marek Cingel
"""Generated by scripts/generate_diagnostic_vocabulary.py; do not edit."""
import pytest
from opentlv import (
    ReaderOperation,
    WriterOperation,
    QueryErrorKind,
    QueryCause,
    SchemaIssue,
    SchemaDefinitionKind,
    CodecOperation,
    CodecCause,
    CodecViolation,
    Severity,
)


VOCABULARY = [
    (ReaderOperation, "TAG", 0, "tag"),
    (ReaderOperation, "LENGTH", 1, "length"),
    (ReaderOperation, "VALUE", 2, "value"),
    (ReaderOperation, "TRAILER", 3, "trailer"),
    (ReaderOperation, "HEADER", 4, "header"),
    (WriterOperation, "TAG", 0, "tag"),
    (WriterOperation, "LENGTH", 1, "length"),
    (WriterOperation, "VALUE", 2, "value"),
    (WriterOperation, "HEADER", 3, "header"),
    (WriterOperation, "TRAILER", 4, "trailer"),
    (WriterOperation, "COPY", 5, "copy"),
    (WriterOperation, "PRESERVE", 6, "preserve"),
    (WriterOperation, "BEGIN", 7, "begin"),
    (WriterOperation, "END", 8, "end"),
    (QueryErrorKind, "NONE", 0, "none"),
    (QueryErrorKind, "SYNTAX", 1, "syntax"),
    (QueryErrorKind, "CAPABILITY", 2, "capability"),
    (QueryErrorKind, "LIMIT", 3, "limit"),
    (QueryErrorKind, "STORAGE", 4, "storage"),
    (QueryErrorKind, "EVENTS", 5, "events"),
    (QueryErrorKind, "SOURCE", 6, "source"),
    (QueryErrorKind, "READER", 7, "reader"),
    (QueryErrorKind, "BINDING", 8, "binding"),
    (QueryErrorKind, "CARDINALITY", 9, "cardinality"),
    (QueryErrorKind, "CODEC", 10, "codec"),
    (QueryErrorKind, "IMAGE_VERSION", 11, "image_version"),
    (QueryErrorKind, "STATE", 12, "state"),
    (QueryErrorKind, "CALLBACK", 13, "callback"),
    (QueryErrorKind, "TYPE", 14, "type"),
    (QueryErrorKind, "IMAGE", 15, "image"),
    (QueryErrorKind, "SCHEMA", 16, "schema"),
    (QueryCause, "NONE", 0, "none"),
    (QueryCause, "READER", 1, "reader"),
    (QueryCause, "CODEC", 2, "codec"),
    (QueryCause, "SCHEMA", 3, "schema"),
    (SchemaIssue, "NONE", 0, "none"),
    (SchemaIssue, "MISSING", 1, "missing"),
    (SchemaIssue, "DUPLICATE", 2, "duplicate"),
    (SchemaIssue, "UNEXPECTED", 3, "unexpected"),
    (SchemaIssue, "KIND", 4, "kind"),
    (SchemaIssue, "LENGTH", 5, "length"),
    (SchemaIssue, "ORDER", 6, "order"),
    (SchemaIssue, "ASSERTION", 7, "assertion"),
    (SchemaIssue, "VALUE", 8, "value"),
    (SchemaIssue, "DEFINITION", 9, "definition"),
    (SchemaDefinitionKind, "UNKNOWN", 0, "unknown"),
    (SchemaDefinitionKind, "TABLE", 1, "table"),
    (SchemaDefinitionKind, "RULE", 2, "rule"),
    (SchemaDefinitionKind, "GROUP", 3, "group"),
    (SchemaDefinitionKind, "TYPE", 4, "type"),
    (SchemaDefinitionKind, "COMPONENT", 5, "component"),
    (CodecOperation, "DECODE", 0, "decode"),
    (CodecOperation, "ENCODE", 1, "encode"),
    (CodecOperation, "MEASURE", 2, "measure"),
    (CodecCause, "NONE", 0, "none"),
    (CodecCause, "READER", 1, "reader"),
    (CodecCause, "SCHEMA", 2, "schema"),
    (CodecViolation, "NONE", 0, "none"),
    (CodecViolation, "RESULT", 1, "result"),
    (CodecViolation, "SIZE", 2, "size"),
    (CodecViolation, "TYPE", 3, "type"),
    (CodecViolation, "UTF8", 4, "utf8"),
    (Severity, "ERROR", 0, "error"),
    (Severity, "WARNING", 1, "warning"),
    (Severity, "INFO", 2, "info"),
]


@pytest.mark.parametrize("category,member,value,label", VOCABULARY)
def test_member_matches_native_vocabulary(category, member, value, label):
    assert category[member].value == value
    assert category(value) is category[member]
    assert category[member].label == label


@pytest.mark.parametrize("category,beyond", [
    (ReaderOperation, 5),
    (WriterOperation, 9),
    (QueryErrorKind, 17),
    (QueryCause, 4),
    (SchemaIssue, 10),
    (SchemaDefinitionKind, 6),
    (CodecOperation, 3),
    (CodecCause, 3),
    (CodecViolation, 5),
    (Severity, 3),
])
def test_next_value_is_unknown(category, beyond):
    assert category(beyond).label == "unknown"
