// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Marek Cingel
// Generated by scripts/generate_diagnostic_vocabulary.py; do not edit.

package tests

import (
	"fmt"
	"testing"

	tlv "github.com/marekcingel/OpenTLV/bindings/go"
)

func TestDiagnosticVocabularyMatchesNative(t *testing.T) {
	cases := []struct {
		value fmt.Stringer
		name  string
	}{
		{tlv.ReaderOperationTag, "tag"},
		{tlv.ReaderOperationLength, "length"},
		{tlv.ReaderOperationValue, "value"},
		{tlv.ReaderOperationTrailer, "trailer"},
		{tlv.ReaderOperationHeader, "header"},
		{tlv.ReaderOperation(5), "unknown"},
		{tlv.WriterOperationTag, "tag"},
		{tlv.WriterOperationLength, "length"},
		{tlv.WriterOperationValue, "value"},
		{tlv.WriterOperationHeader, "header"},
		{tlv.WriterOperationTrailer, "trailer"},
		{tlv.WriterOperationCopy, "copy"},
		{tlv.WriterOperationPreserve, "preserve"},
		{tlv.WriterOperationBegin, "begin"},
		{tlv.WriterOperationEnd, "end"},
		{tlv.WriterOperation(9), "unknown"},
		{tlv.QueryErrorKindNone, "none"},
		{tlv.QueryErrorKindSyntax, "syntax"},
		{tlv.QueryErrorKindCapability, "capability"},
		{tlv.QueryErrorKindLimit, "limit"},
		{tlv.QueryErrorKindStorage, "storage"},
		{tlv.QueryErrorKindEvents, "events"},
		{tlv.QueryErrorKindSource, "source"},
		{tlv.QueryErrorKindReader, "reader"},
		{tlv.QueryErrorKindBinding, "binding"},
		{tlv.QueryErrorKindCardinality, "cardinality"},
		{tlv.QueryErrorKindCodec, "codec"},
		{tlv.QueryErrorKindImageVersion, "image_version"},
		{tlv.QueryErrorKindState, "state"},
		{tlv.QueryErrorKindCallback, "callback"},
		{tlv.QueryErrorKindType, "type"},
		{tlv.QueryErrorKindImage, "image"},
		{tlv.QueryErrorKind(16), "unknown"},
		{tlv.SchemaIssueNone, "none"},
		{tlv.SchemaIssueMissing, "missing"},
		{tlv.SchemaIssueDuplicate, "duplicate"},
		{tlv.SchemaIssueUnexpected, "unexpected"},
		{tlv.SchemaIssueKind, "kind"},
		{tlv.SchemaIssueLength, "length"},
		{tlv.SchemaIssueOrder, "order"},
		{tlv.SchemaIssueAssertion, "assertion"},
		{tlv.SchemaIssueValue, "value"},
		{tlv.SchemaIssueDefinition, "definition"},
		{tlv.SchemaIssue(10), "unknown"},
		{tlv.SchemaDefinitionKindUnknown, "unknown"},
		{tlv.SchemaDefinitionKindTable, "table"},
		{tlv.SchemaDefinitionKindRule, "rule"},
		{tlv.SchemaDefinitionKindGroup, "group"},
		{tlv.SchemaDefinitionKindType, "type"},
		{tlv.SchemaDefinitionKindComponent, "component"},
		{tlv.SchemaDefinitionKind(6), "unknown"},
		{tlv.CodecOperationDecode, "decode"},
		{tlv.CodecOperationEncode, "encode"},
		{tlv.CodecOperationMeasure, "measure"},
		{tlv.CodecOperation(3), "unknown"},
		{tlv.CodecCauseNone, "none"},
		{tlv.CodecCauseReader, "reader"},
		{tlv.CodecCauseSchema, "schema"},
		{tlv.CodecCause(3), "unknown"},
		{tlv.CodecViolationNone, "none"},
		{tlv.CodecViolationResult, "result"},
		{tlv.CodecViolationSize, "size"},
		{tlv.CodecViolationType, "type"},
		{tlv.CodecViolationUtf8, "utf8"},
		{tlv.CodecViolation(5), "unknown"},
		{tlv.SeverityError, "error"},
		{tlv.SeverityWarning, "warning"},
		{tlv.SeverityInfo, "info"},
		{tlv.Severity(3), "unknown"},
	}
	for _, c := range cases {
		if got := c.value.String(); got != c.name {
			t.Errorf("%T(%v): got %q, want %q", c.value, c.value, got, c.name)
		}
	}
}
